# Generated by Django 5.2.7 on 2026-02-03 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0002_projects_completed_date_projects_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='ApprovalResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approval_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='schedular.approvalrequest')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
