# Generated by Django 5.2.7 on 2026-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0003_remove_approvalrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='reference_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='approvalresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
