# Generated by Django 5.2.7 on 2026-02-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0004_alter_approvalrequest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='is_approved',
        ),
    ]
