# Generated by Django 5.2.7 on 2026-02-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0010_add_task_start_date_and_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.DateTimeField(auto_now_add=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Hours worked', max_digits=5)),
                ('minutes_worked', models.IntegerField(default=0, help_text='Total minutes worked')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('STOPPED', 'Stopped'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('work_notes', models.TextField(blank=True, help_text='Notes about the work done', null=True)),
                ('is_task_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('catalog_type', models.CharField(choices=[('PROJECT', 'Project'), ('TASK', 'Task'), ('COURSE', 'Course'), ('ROUTINE', 'Routine'), ('CUSTOM', 'Custom Work')], max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('work_date', models.DateField()),
                ('planned_hours', models.IntegerField(default=0)),
                ('spending_hours', models.IntegerField(default=0)),
                ('started_working_hours', models.TimeField(blank=True, null=True)),
                ('ending_working_hours', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('user', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_plan_date', models.DateField()),
                ('replanned_date', models.DateField(blank=True, null=True)),
                ('minutes_left', models.IntegerField(default=0, help_text='Estimated minutes left to complete')),
                ('reason', models.TextField(blank=True, help_text='Reason for not completing', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REPLANNED', 'Replanned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_items', to='schedular.activitylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('planned_duration_minutes', models.IntegerField(help_text='Planned duration in minutes')),
                ('order_index', models.IntegerField(default=0, help_text="Order in today's plan")),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('STARTED', 'Started'), ('IN_ACTIVITY', 'In Activity Log'), ('COMPLETED', 'Completed'), ('MOVED_TO_PENDING', 'Moved to Pending')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan_date', 'order_index'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AddField(
            model_name='projects',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catalog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='schedular.projects'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='schedular.task'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_activities', to='schedular.projects'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activities', to='schedular.task'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todayplan',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_items', to='schedular.catalog'),
        ),
        migrations.AddField(
            model_name='todayplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='today_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pending',
            name='today_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='schedular.todayplan'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='today_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='schedular.todayplan'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterUniqueTogether(
            name='todayplan',
            unique_together={('user', 'plan_date', 'order_index')},
        ),
    ]
