# Generated by Django 5.2.7 on 2026-02-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0011_activitylog_catalog_dailyactivity_daysession_pending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
    ]
