# Generated by Django 5.2.7 on 2026-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0013_teaminstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='todayplan',
            name='quadrant',
            field=models.CharField(choices=[('Q1', 'Q1: Do First (Urgent & Important)'), ('Q2', 'Q2: Schedule (Important, Not Urgent)'), ('Q3', 'Q3: Delegate (Urgent, Not Important)'), ('Q4', 'Q4: Eliminate (Not Urgent, Not Important)')], default='Q2', help_text='Eisenhower Matrix quadrant', max_length=2),
        ),
    ]
