# Generated by Django 5.2.7 on 2026-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0014_catalog_progress_percentage_todayplan_quadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto/System Default')], default='auto', max_length=10),
        ),
    ]
