# Generated by Django 5.2.7 on 2026-02-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0014_notification'),
        ('schedular', '0015_user_theme_preference'),
    ]

    operations = [
    ]
