# Generated by Django 5.2.7 on 2026-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0016_merge_0014_notification_0015_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='progress_weight',
            field=models.IntegerField(default=25, help_text='Weight of this subtask in percentage (e.g., 25 for 25%)'),
        ),
        migrations.AddField(
            model_name='task',
            name='figma_link',
            field=models.URLField(blank=True, help_text='Figma design link', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository or issue link', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='next_occurrence',
            field=models.DateField(blank=True, help_text='For recurring tasks', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('RECURRING', 'Recurring'), ('ROUTINE', 'Routine')], default='STANDARD', max_length=20),
        ),
    ]
