# Generated by Django 5.2.7 on 2026-02-12 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0017_subtask_progress_weight_task_figma_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
