# Generated by Django 5.2.7 on 2026-02-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0018_task_project_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
    ]
