# Generated by Django 5.2.7 on 2026-02-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0020_stickynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayplan',
            name='custom_description',
            field=models.TextField(blank=True, help_text='Description for custom tasks', null=True),
        ),
        migrations.AddField(
            model_name='todayplan',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Title for custom tasks', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='todayplan',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_items', to='schedular.catalog'),
        ),
    ]
