# Generated by Django 5.2.7 on 2026-02-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0021_todayplan_custom_description_todayplan_custom_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayplan',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, help_text='Can be set later in activity log', null=True),
        ),
        migrations.AlterField(
            model_name='todayplan',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, help_text='Can be set later in activity log', null=True),
        ),
    ]
