# Generated by Django 5.2.7 on 2026-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0022_alter_todayplan_scheduled_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='extra_minutes',
            field=models.IntegerField(default=0, help_text='Extra minutes worked beyond planned time'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('STOPPED', 'Stopped'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
