# Generated by Django 5.2.7 on 2026-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0023_pending_extra_minutes_alter_activitylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='extra_minutes',
            field=models.IntegerField(default=0, help_text='Extra minutes worked beyond planned time'),
        ),
    ]
