# Generated by Django 5.2.7 on 2026-02-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0024_activitylog_extra_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_lead',
            field=models.ForeignKey(blank=True, help_text='Team Lead for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
