# Generated by Django 5.2.7 on 2026-02-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0025_user_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalog_type',
            field=models.CharField(max_length=50),
        ),
    ]
