# Generated by Django 5.2.7 on 2026-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0026_alter_catalog_catalog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('PENDING_APPROVAL', 'Pending Approval')], default='PENDING', max_length=20),
        ),
    ]
