# Generated by Django 5.2.7 on 2026-02-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0027_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='approval_status',
            field=models.CharField(blank=True, help_text='Current approval status: PENDING_COMPLETION, etc.', max_length=50, null=True),
        ),
    ]
