# Generated by Django 5.2.7 on 2026-02-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0031_enhance_employee_model_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hrm_employee_id',
            field=models.CharField(blank=True, help_text='Employee ID from HRM system (for linking)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active_in_hrm',
            field=models.BooleanField(default=True, help_text='Active status from HRM (source of truth)'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, help_text='Date employee joined', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='Job designation from HRM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_name',
            field=models.CharField(blank=True, help_text='Full name from HRM', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, help_text='Employment type: intern, permanent, Trainee, Consultant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hrm_department',
            field=models.CharField(blank=True, help_text='Department name from HRM', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hrm_employee_id',
            field=models.CharField(blank=True, help_text='Employee ID from HRM system', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_in_hrm',
            field=models.BooleanField(default=True, help_text='Active status from HRM system'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, help_text='Last time employee data was synced from HRM', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Work location', max_length=200, null=True),
        ),
    ]
