# Generated by Django 5.2.7 on 2026-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0032_employee_hrm_employee_id_employee_is_active_in_hrm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='actual_start_time',
            field=models.DateTimeField(),
        ),
    ]
