# Generated by Django 5.2.7 on 2026-03-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0033_alter_activitylog_actual_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminstruction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_instructions', to='schedular.projects'),
        ),
    ]
