# Generated by Django 5.2.7 on 2026-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0034_alter_teaminstruction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
