# Generated by Django 5.2.7 on 2026-03-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0035_projects_rejection_reason_task_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayplan',
            name='is_unplanned',
            field=models.BooleanField(default=False, help_text='True if this task was started directly from the catalog'),
        ),
    ]
