# Generated by Django 5.2.7 on 2026-04-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0036_todayplan_is_unplanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='planned_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
