# Generated by Django 5.2.7 on 2026-04-03 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0038_task_planned_hours_dailyplanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
