# Generated by Django 5.2.7 on 2026-04-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0039_subtask_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_lead',
        ),
    ]
