# Generated by Django 5.2.7 on 2026-04-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0040_remove_task_project_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayplan',
            name='is_unplanned',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_unplanned',
            field=models.BooleanField(default=False, help_text='True if this work was on an unplanned task'),
        ),
    ]
