# Generated by Django 5.2.7 on 2026-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0041_move_is_unplanned_to_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayplan',
            name='is_unplanned',
            field=models.BooleanField(default=False, help_text='True if this was an unplanned addition to the daily plan'),
        ),
    ]
