# Generated by Django 5.2.7 on 2026-04-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0042_todayplan_is_unplanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayplan',
            name='quadrant',
            field=models.CharField(choices=[('Q1', 'Q1: Do First (Urgent & Important)'), ('Q2', 'Q2: Schedule (Important, Not Urgent)'), ('Q3', 'Q3: Delegate (Urgent, Not Important)'), ('Q4', 'Q4: Eliminate (Not Urgent, Not Important)'), ('inbox', 'Inbox (Unquadranted)')], default='Q2', help_text='Eisenhower Matrix quadrant', max_length=5),
        ),
    ]
