# Generated by Django 5.2.7 on 2026-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0043_fix_quadrant_and_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
