# Generated by Django 5.2.7 on 2026-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0044_stickynote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quick_notes_label',
            field=models.CharField(default='QUICK NOTES', max_length=100),
        ),
    ]
