# Generated by Django 5.2.7 on 2026-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0045_user_quick_notes_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='work_notes',
            field=models.TextField(blank=True, help_text='Work notes synced from activity log', null=True),
        ),
    ]
