# Generated by Django 5.2.7 on 2026-04-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0046_pending_work_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickynote',
            options={'ordering': ['order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='stickynote',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
