# Generated by Django 5.2.7 on 2026-04-28 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0049_task_client_remove_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='admin_remark',
            field=models.TextField(blank=True, help_text='Remark added by admin/teamlead for this activity log', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='admin_remark_at',
            field=models.DateTimeField(blank=True, help_text='When the remark was added', null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='admin_remark_by',
            field=models.ForeignKey(blank=True, help_text='User who added the remark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_remarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
