# Generated by Django 5.2.7 on 2026-04-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedular', '0050_add_admin_remark_to_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client for routine work items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='schedular.client'),
        ),
    ]
