# Generated by Django 5.0.3 on 2024-05-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='walkin',
            name='InterviewSchedule',
        ),
        migrations.RemoveField(
            model_name='offeredposition',
            name='WalkIn',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='InterviewSchedule',
        ),
        migrations.DeleteModel(
            name='OfferedPosition',
        ),
        migrations.DeleteModel(
            name='WalkIn',
        ),
    ]
