# Generated by Django 5.0.3 on 2024-05-07 06:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0002_remove_activity_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('No_Of_Possitions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('Activity_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('targets', models.IntegerField(blank=True, null=True)),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activatys', to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(blank=True, default=0, null=True)),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.position')),
            ],
        ),
        migrations.CreateModel(
            name='WalkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(default=0)),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('InterviewSchedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.interviewschedule')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('achieved', models.IntegerField(default=0)),
                ('WalkIn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.walkin')),
            ],
        ),
    ]
