# Generated by Django 5.0.3 on 2024-05-07 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0003_position_activity_interviewschedule_walkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='Date_of_Joining',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
