# Generated by Django 5.0.3 on 2024-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0004_offerlettermodel_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='Accept_status',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Reject', 'Reject')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
