# Generated by Django 5.0.3 on 2024-05-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0001_initial'),
        ('HRM_App', '0005_offerlettermodel_accept_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='employeeProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.employeeinformation'),
        ),
    ]
