# Generated by Django 5.0.3 on 2024-05-08 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0006_employeedatamodel_employeeprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedatamodel',
            old_name='designation',
            new_name='position',
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.designationmodel'),
        ),
    ]
