# Generated by Django 5.0.3 on 2024-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0007_rename_designation_employeedatamodel_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='Mail_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerlettermodel',
            name='Date_of_Joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
