# Generated by Django 5.0.3 on 2024-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0008_offerlettermodel_mail_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettermodel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
