# Generated by Django 5.0.3 on 2024-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0009_alter_offerlettermodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatamodel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
