# Generated by Django 5.0.3 on 2024-05-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0010_alter_employeedatamodel_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deparments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
