# Generated by Django 5.0.3 on 2024-05-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0011_deparments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.deparments'),
        ),
    ]
