# Generated by Django 5.0.3 on 2024-05-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0012_employeedatamodel_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationmodel',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.deparments'),
        ),
        migrations.AlterField(
            model_name='employeedatamodel',
            name='Designation',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Employee', 'Employee'), ('Recruiter', 'Recruiter')], max_length=100, null=True),
        ),
    ]
