# Generated by Django 5.0.3 on 2024-05-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0013_designationmodel_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedatamodel',
            name='Department',
        ),
    ]
