# Generated by Django 5.0.3 on 2024-05-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0014_remove_employeedatamodel_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedatamodel',
            name='position',
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.designationmodel'),
        ),
    ]
