# Generated by Django 5.0.3 on 2024-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0015_remove_employeedatamodel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_verificationmodel',
            name='CandidatePerformanceLevel',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bg_verificationmodel',
            name='Comments_On_Candidate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
