# Generated by Django 5.0.3 on 2024-05-10 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0016_alter_bg_verificationmodel_candidateperformancelevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_Id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('weight', models.CharField(blank=True, max_length=15, null=True)),
                ('height', models.CharField(blank=True, max_length=15, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.candidateapplicationmodel')),
                ('Offered_Instance', models.ManyToManyField(blank=True, null=True, to='HRM_App.offerlettermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employeedatamodel',
            name='employeeProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
    ]
