# Generated by Django 5.0.3 on 2024-05-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0017_employeeinformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Date',
            new_name='Activity_added_Date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='achieved',
        ),
        migrations.CreateModel(
            name='DailyAchives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('achieved_Date', models.DateField(blank=True, null=True)),
                ('Activity_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.activity')),
            ],
        ),
    ]
