# Generated by Django 5.0.3 on 2024-05-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0018_rename_date_activity_activity_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='ProfileVerification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
