# Generated by Django 5.0.3 on 2024-05-17 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0019_employeeinformation_profileverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='Reporting_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Repotinf_to', to='HRM_App.employeedatamodel'),
        ),
    ]
