# Generated by Django 5.0.3 on 2024-05-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0020_employeedatamodel_reporting_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='Designation',
        ),
    ]
