# Generated by Django 5.0.3 on 2024-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0021_remove_employeeinformation_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='ProfileVerification',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed')], max_length=100, null=True),
        ),
    ]
