# Generated by Django 5.0.3 on 2024-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0022_alter_employeeinformation_profileverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='CTC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='Emp_Current_Roll',
            field=models.CharField(blank=True, choices=[('intern', 'Intern_Employee'), ('generalemployee', 'General_Employee')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='WorkLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='internship_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='internship_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='probation_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='probation_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='under_probation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
