# Generated by Django 5.0.3 on 2024-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0023_offerlettermodel_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='internship_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='probhation_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=100, null=True),
        ),
    ]
