# Generated by Django 5.0.3 on 2024-05-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0024_offerlettermodel_internship_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerlettermodel',
            old_name='Emp_Current_Roll',
            new_name='Emp_Current_Role',
        ),
    ]
