# Generated by Django 5.0.3 on 2024-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0025_rename_emp_current_roll_offerlettermodel_emp_current_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerlettermodel',
            unique_together={('CandidateId',)},
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('in_active', 'In_Active')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='Employeement_Type',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('permanent', 'permanent')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='probation_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='offerlettermodel',
            name='Emp_Current_Role',
        ),
        migrations.RemoveField(
            model_name='offerlettermodel',
            name='under_probation',
        ),
    ]
