# Generated by Django 5.0.3 on 2024-05-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0026_alter_offerlettermodel_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerlettermodel',
            old_name='probhation_status',
            new_name='is_probation_status',
        ),
    ]
