# Generated by Django 5.0.3 on 2024-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0027_rename_probhation_status_offerlettermodel_is_probation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='notice_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
