# Generated by Django 5.0.3 on 2024-05-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0029_alter_offerlettermodel_probation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
