# Generated by Django 5.0.3 on 2024-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0030_employeeinformation_hired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
