# Generated by Django 5.0.3 on 2024-05-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0031_employeeinformation_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='GeneralSkills',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='GeneralSkills_with_Exp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='SoftSkills',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='SoftSkills_with_Exp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='TechnicalSkills',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='TechnicalSkills_with_Exp',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
