# Generated by Django 5.0.3 on 2024-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0032_alter_candidateapplicationmodel_generalskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='ContactedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='ExpectedSalary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='FirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='JobPortalSource',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='PrimaryContact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
