# Generated by Django 5.0.3 on 2024-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0033_alter_candidateapplicationmodel_contactedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Experience',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Fresher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
