# Generated by Django 5.0.3 on 2024-05-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0034_alter_candidateapplicationmodel_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyachives',
            old_name='achieved_Date',
            new_name='Date',
        ),
    ]
