# Generated by Django 5.0.3 on 2024-05-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0035_rename_achieved_date_dailyachives_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to='HRM_App.employeedatamodel'),
        ),
    ]
