# Generated by Django 5.0.3 on 2024-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0036_activity_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkin',
            name='InterviewSchedule',
        ),
        migrations.RenameField(
            model_name='interviewschedule',
            old_name='Date',
            new_name='Interview_Added_Date',
        ),
        migrations.RemoveField(
            model_name='interviewschedule',
            name='achieved',
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='targets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='OfferedPosition',
        ),
        migrations.DeleteModel(
            name='WalkIn',
        ),
    ]
