# Generated by Django 5.0.3 on 2024-05-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0037_remove_walkin_interviewschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='Candidate_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.candidateapplicationmodel'),
        ),
    ]
