# Generated by Django 5.0.3 on 2024-05-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0038_alter_employeeinformation_candidate_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewSchedule',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
