# Generated by Django 5.0.3 on 2024-05-26 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0039_delete_interviewschedule_delete_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('No_Of_Open_Possitions', models.IntegerField(default=0)),
                ('No_Of_Closed_Possitions', models.IntegerField(default=0)),
                ('targets', models.IntegerField(blank=True, default=0, null=True)),
                ('Interview_Added_Date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Interview', to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAchivesInterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Interview_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.interviewschedule')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('InterviewSchedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.interviewschedule')),
            ],
        ),
        migrations.CreateModel(
            name='WalkIns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('InterviewSchedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.interviewschedule')),
            ],
        ),
    ]
