# Generated by Django 5.0.3 on 2024-05-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0040_interviewschedule_dailyachivesinterviewschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='Assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel'),
        ),
    ]
