# Generated by Django 5.0.3 on 2024-05-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0041_interviewschedule_assigned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyachivesinterviewschedule',
            old_name='Interview_instance',
            new_name='InterviewSchedule',
        ),
    ]
