# Generated by Django 5.0.3 on 2024-05-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0042_rename_interview_instance_dailyachivesinterviewschedule_interviewschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatamodel',
            name='employeeProfile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
    ]
