# Generated by Django 5.0.3 on 2024-05-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0043_alter_employeedatamodel_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='not_type',
            field=models.CharField(blank=True, choices=[('cal', 'cal'), ('scr_assign', 'scr_assign'), ('int_assign', 'int_assign'), ('scr_com', 'scr_com'), ('int_com', 'int_com')], max_length=100, null=True),
        ),
    ]
