# Generated by Django 5.0.3 on 2024-05-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0044_notification_not_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='condidate_id',
            new_name='candidate_id',
        ),
    ]
