# Generated by Django 5.0.3 on 2024-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0045_rename_condidate_id_notification_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationmodel',
            name='dep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
