# Generated by Django 5.0.3 on 2024-05-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0046_designationmodel_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designationmodel',
            name='dep',
        ),
    ]
