# Generated by Django 5.0.3 on 2024-05-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0047_remove_designationmodel_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Fresher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='JobPortalSource',
            field=models.CharField(blank=True, choices=[('noukari', 'Noukari'), ('linkedin', 'Linkedin'), ('foundit', 'Foundit'), ('others', 'Others')], max_length=100, null=True),
        ),
    ]
