# Generated by Django 5.0.3 on 2024-05-31 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0048_alter_candidateapplicationmodel_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='JobPortalSource',
            field=models.CharField(blank=True, choices=[('naukri', 'Naukri'), ('linkedin', 'Linkedin'), ('foundit', 'Foundit'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='MeritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='SpouseDesignation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='interview_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.interviewschedulmodel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='screeingreview',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.screeningassigningmodel'),
        ),
    ]
