# Generated by Django 5.0.3 on 2024-05-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0049_alter_candidateapplicationmodel_jobportalsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='InterviewRoundName',
            field=models.CharField(choices=[('technical_round', 'Technical_Round'), ('hr_round', 'HR_Round')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='InterviewType',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('ofline', 'Ofline')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='TaskAssigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
