# Generated by Django 5.0.3 on 2024-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0050_alter_interviewschedulmodel_interviewroundname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='InterviewType',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='AgeGroupSuitability',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True),
        ),
    ]
