# Generated by Django 5.0.3 on 2024-06-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0051_alter_interviewschedulmodel_interviewtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='No_Of_Closed_Possitions',
        ),
        migrations.RemoveField(
            model_name='interviewschedule',
            name='targets',
        ),
        migrations.AlterField(
            model_name='review',
            name='MeritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('marrid', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True),
        ),
    ]
