# Generated by Django 5.0.3 on 2024-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0052_remove_interviewschedule_no_of_closed_possitions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='No_Of_Open_Possitions',
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='targets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
