# Generated by Django 5.0.3 on 2024-06-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0055_alter_candidateapplicationmodel_final_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True),
        ),
    ]
