# Generated by Django 5.0.3 on 2024-06-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0057_alter_employeedatamodel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatamodel',
            name='Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM_App.designationmodel'),
        ),
        migrations.AlterField(
            model_name='employeedatamodel',
            name='Reporting_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Repotinf_to', to='HRM_App.employeedatamodel'),
        ),
    ]
