# Generated by Django 5.0.3 on 2024-06-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0058_alter_employeedatamodel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Documents_Upload_Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Uploaded', 'Uploaded')], default='Pending', max_length=100, null=True),
        ),
    ]
