# Generated by Django 5.0.3 on 2024-06-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0060_alter_candidateapplicationmodel_final_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deparments',
            name='Dep_Name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='designationmodel',
            name='Department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HRM_App.deparments'),
        ),
    ]
