# Generated by Django 5.0.3 on 2024-06-03 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0061_alter_deparments_dep_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalledCandidatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('fresher', 'Fresher'), ('experience', 'Experience')], max_length=100)),
                ('interview_scheduled_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('called_date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
