# Generated by Django 5.0.3 on 2024-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0064_alter_hrfinalstatusmodel_final_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='TravellBy',
            new_name='ModeOfCommutation',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='StaysWith',
            new_name='Residingat',
        ),
        migrations.RemoveField(
            model_name='review',
            name='FatherDesignation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='MotherDesignation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='no_of_sibilings',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sibilingsDesignation',
        ),
        migrations.AddField(
            model_name='review',
            name='About_Family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='Mother_Tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
