# Generated by Django 5.0.3 on 2024-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0065_rename_travellby_review_modeofcommutation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Screening_Status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled For Next Round'), ('rejected', 'Rejected'), ('scheduled interview to client', 'Scheduled Interview to Client')], max_length=100, null=True),
        ),
    ]
