# Generated by Django 5.0.3 on 2024-06-06 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0066_alter_review_screening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningassigningmodel',
            name='Candidate',
            field=models.OneToOneField(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recruiter', to='HRM_App.candidateapplicationmodel'),
        ),
    ]
