# Generated by Django 5.0.3 on 2024-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0068_alter_review_screening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettermodel',
            name='Accept_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettermodel',
            name='internship_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offerlettermodel',
            name='is_probation_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], max_length=100, null=True),
        ),
    ]
