# Generated by Django 5.0.3 on 2024-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0069_alter_offerlettermodel_accept_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='Other_jps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
