# Generated by Django 5.0.3 on 2024-06-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0070_candidateapplicationmodel_other_jps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedulmodel',
            name='TaskAssigned',
        ),
        migrations.AddField(
            model_name='interviewschedulmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screeningassigningmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='InterviewRoundName',
            field=models.CharField(choices=[('technical_round', 'Technical_Round'), ('manager_round', 'Manager_Round'), ('hr_round', 'HR_Round')], max_length=100),
        ),
    ]
