# Generated by Django 5.0.3 on 2024-06-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0071_remove_interviewschedulmodel_taskassigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningassigningmodel',
            name='status',
        ),
    ]
