# Generated by Django 5.0.3 on 2024-06-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0072_remove_screeningassigningmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='CertificateSubmittion',
            new_name='OwnLoptop',
        ),
    ]
