# Generated by Django 5.0.3 on 2024-06-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0073_rename_certificatesubmittion_review_ownloptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Screening_Status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled For Next Round'), ('rejected', 'Rejected'), ('to_client', 'Scheduled Interview to Client'), ('walkout', 'Walkout')], max_length=100, null=True),
        ),
    ]
