# Generated by Django 5.0.3 on 2024-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0074_alter_review_screening_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calledcandidatesmodel',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calledcandidatesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('interview_scheduled', 'Interview_Scheduled'), ('rejected', 'Rejected'), ('to_client', 'Consider_to_Client')], max_length=100, null=True),
        ),
    ]
