# Generated by Django 5.0.3 on 2024-06-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0076_alter_candidateapplicationmodel_final_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='SpouseDesignation',
            new_name='SpouseName',
        ),
    ]
