# Generated by Django 5.0.3 on 2024-06-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0077_rename_spousedesignation_review_spousename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='applied_list_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='interview_shedule_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='screening_shedule_access',
            field=models.BooleanField(default=False),
        ),
    ]
