# Generated by Django 5.0.3 on 2024-06-18 04:55

import HRM_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0078_employeedatamodel_applied_list_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Coding_Questions_Score',
            field=models.IntegerField(blank=True, help_text='Coding Questions Score', null=True, validators=[HRM_App.models.validate_positive]),
        ),
    ]
