# Generated by Django 5.0.3 on 2024-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0079_review_coding_questions_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Coding_Questions_Score',
            field=models.IntegerField(blank=True, help_text='Coding Questions Score', null=True),
        ),
    ]
