# Generated by Django 5.0.3 on 2024-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0080_alter_review_coding_questions_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='AchivementOrientation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
