# Generated by Django 5.0.3 on 2024-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0082_alter_hrfinalstatusmodel_final_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='final_status_access',
            field=models.BooleanField(default=False),
        ),
    ]
