# Generated by Django 5.0.3 on 2024-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0083_employeedatamodel_final_status_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='no_of_kids',
            new_name='About_Childrens',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ScreeningFeedback',
        ),
        migrations.AddField(
            model_name='review',
            name='FathersDesignation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='FathersName',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='Leagel_cases',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='MothersDesignation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='MothersName',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='SpouseDesignation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='devorced_statement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='MeritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('marrid', 'Married'), ('divorced', 'Divorced')], max_length=10, null=True),
        ),
    ]
