# Generated by Django 5.0.3 on 2024-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0085_alter_candidateapplicationmodel_final_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatamodel',
            name='Designation',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Employee', 'Employee'), ('Recruiter', 'Recruiter')], max_length=100, null=True),
        ),
    ]
