# Generated by Django 5.0.3 on 2024-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0087_alter_review_about_childrens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='Employeement_Type',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('permanent', 'permanent')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='probation_status',
            field=models.CharField(blank=True, choices=[('probationer', 'Probationer'), ('confirmed', 'Confirmed')], max_length=100, null=True),
        ),
    ]
