# Generated by Django 5.0.3 on 2024-06-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0088_employeeinformation_employeement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyachivesinterviewschedule',
            name='achieved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offeredposition',
            name='achieved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='walkins',
            name='achieved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
