# Generated by Django 5.0.3 on 2024-06-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0090_alter_candidateapplicationmodel_final_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
