# Generated by Django 5.0.3 on 2024-06-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0091_alter_registrationmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='total',
        ),
        migrations.AddField(
            model_name='interviewschedulmodel',
            name='Out_EMP_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedulmodel',
            name='inside_interviewer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='HRM_App.employeedatamodel'),
        ),
    ]
