# Generated by Django 5.0.3 on 2024-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0092_remove_activity_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='Offers_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='Walkins_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='intrview_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
