# Generated by Django 5.0.3 on 2024-06-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0093_interviewschedule_offers_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewschedule',
            name='intrview_target',
        ),
    ]
