# Generated by Django 5.0.3 on 2024-06-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0094_remove_interviewschedule_intrview_target'),
    ]

    