# Generated by Django 5.0.3 on 2024-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0095_review_interviewername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='Employeement_Type',
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='probation_status',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('probationer', 'Probationer'), ('confirmed', 'Confirmed')], max_length=100, null=True),
        ),
    ]
