# Generated by Django 5.0.3 on 2024-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0096_remove_employeeinformation_employeement_type_and_more'),
    ]

    
