# Generated by Django 5.0.3 on 2024-06-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0097_employeeinformation_employeement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShifts_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift_Name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('start_shift', models.TimeField(blank=True, null=True)),
                ('end_shift', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWeekoffs_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekoffs', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='EmployeeShifts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeshifts_model'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='EmployeeWeekoffs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeweekoffs_model'),
        ),
    ]
