# Generated by Django 5.0.3 on 2024-06-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0098_employeeshifts_model_employeeweekoffs_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='EmployeeWeekoffs',
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='EmployeeWeekoffs',
            field=models.ManyToManyField(to='HRM_App.employeeweekoffs_model'),
        ),
    ]
