# Generated by Django 5.0.3 on 2024-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0099_remove_employeeinformation_employeeweekoffs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeweekoffs_model',
            name='weekoffs',
            field=models.CharField(blank=True, choices=[(0, 'Su'), (1, 'Mo'), (2, 'Tu'), (3, 'We'), (4, 'Th'), (5, 'Fr'), (6, 'Sa')], max_length=100, null=True, unique=True),
        ),
    ]
