# Generated by Django 5.0.3 on 2024-07-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0101_alter_employeeweekoffs_model_weekoffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='EmployeeWeekoffs',
        ),
    ]
