# Generated by Django 5.0.3 on 2024-07-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0102_remove_employeeinformation_employeeweekoffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeWeekoffs_Model',
        ),
    ]
