# Generated by Django 5.0.3 on 2024-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
    ]

    