# Generated by Django 5.0.3 on 2024-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0104_screeningassigningmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
