# Generated by Django 5.0.3 on 2024-07-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0105_candidateapplicationmodel_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_verificationmodel',
            name='Documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.documents_upload_model'),
        ),
        migrations.AlterField(
            model_name='bg_verificationmodel',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.candidateapplicationmodel'),
        ),
    ]
