# Generated by Django 5.0.3 on 2024-07-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0106_alter_bg_verificationmodel_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettermodel',
            name='position',
        ),
    ]
