# Generated by Django 5.0.3 on 2024-07-17 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0107_remove_offerlettermodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.designationmodel'),
        ),
    ]
