# Generated by Django 5.0.3 on 2024-07-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0108_offerlettermodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
