# Generated by Django 5.0.3 on 2024-07-18 04:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0110_alter_offerlettermodel_fixed_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='VerifiedDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='letter_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifed_by', to='HRM_App.employeedatamodel'),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerlettermodel',
            name='Letter_sended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_by', to='HRM_App.employeedatamodel'),
        ),
    ]
