# Generated by Django 5.0.3 on 2024-07-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0111_offerlettermodel_verifieddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettermodel',
            name='verification_status',
        ),
    ]
