# Generated by Django 5.0.3 on 2024-07-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0112_remove_offerlettermodel_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], max_length=100, null=True),
        ),
    ]
