# Generated by Django 5.0.3 on 2024-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0113_offerlettermodel_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
