# Generated by Django 5.0.3 on 2024-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0114_offerlettermodel_approval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettermodel',
            name='CTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
