# Generated by Django 5.0.3 on 2024-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0115_alter_offerlettermodel_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettermodel',
            name='VerifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
