# Generated by Django 5.0.3 on 2024-07-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0116_alter_offerlettermodel_verifieddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettermodel',
            name='fixed_salary',
        ),
    ]
