# Generated by Django 5.0.3 on 2024-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0117_remove_offerlettermodel_fixed_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettermodel',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=100, null=True),
        ),
    ]
