# Generated by Django 5.0.3 on 2024-07-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0118_alter_offerlettermodel_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='letter_prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_prepared_by', to='HRM_App.employeedatamodel'),
        ),
    ]
