# Generated by Django 5.0.3 on 2024-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0119_offerlettermodel_letter_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='letter_prepared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
