# Generated by Django 5.0.3 on 2024-07-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0120_offerlettermodel_letter_prepared_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='Letter_sended_status',
            field=models.BooleanField(default=False),
        ),
    ]
