# Generated by Django 5.0.3 on 2024-07-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0122_alter_candidateapplicationmodel_final_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bg_verificationmodel',
            name='FinalVerifyStatus',
        ),
    ]
