# Generated by Django 5.0.3 on 2024-07-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0123_remove_bg_verificationmodel_finalverifystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
