# Generated by Django 5.0.3 on 2024-07-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0124_employeeinformation_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='permanent_City',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='present_City',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='present_pincode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='present_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
