# Generated by Django 5.0.3 on 2024-07-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0125_employeeinformation_permanent_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformation',
            name='pincode',
        ),
    ]
