# Generated by Django 5.0.3 on 2024-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0126_remove_employeeinformation_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='form_submetted_status',
            field=models.BooleanField(default=False),
        ),
    ]
