# Generated by Django 5.0.3 on 2024-07-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0127_employeeinformation_form_submetted_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinformation',
            old_name='form_submetted_status',
            new_name='form_submitted_status',
        ),
    ]
