# Generated by Django 5.0.3 on 2024-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0128_rename_form_submetted_status_employeeinformation_form_submitted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='date_of_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='restricted_leave_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
