# Generated by Django 5.0.3 on 2024-07-25 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0129_employeeinformation_date_of_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progile_verifier', to='HRM_App.employeedatamodel'),
        ),
    ]
