# Generated by Django 5.0.3 on 2024-07-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0130_employeedatamodel_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='Employeement_Type',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('permanent', 'permanent')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='internship_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='internship_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='probation_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='probation_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='InterviewerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screeningassigningmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='probation_status',
            field=models.CharField(blank=True, choices=[('probationer', 'Probationer'), ('confirmed', 'Confirmed')], max_length=100, null=True),
        ),
    ]
