# Generated by Django 5.0.3 on 2024-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0133_remove_candidateapplicationmodel_appling_for'),
    ]

    