# Generated by Django 5.0.3 on 2024-08-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0134_candidateapplicationmodel_appling_for_and_more'),
    ]

    