# Generated by Django 5.0.3 on 2024-08-20 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0136_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='documents_upload_model',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        
        migrations.AlterField(
            model_name='bg_verificationmodel',
            name='Candidate_Behavior_Feedback',
            field=models.FloatField(blank=True, help_text='Your feedback on Candidates behavior, integrity & work ethics', null=True),
        ),
        migrations.AlterField(
            model_name='bg_verificationmodel',
            name='TeamSize',
            field=models.IntegerField(blank=True, null=True),
        )
        
    ]
