# Generated by Django 5.0.3 on 2024-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0137_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='offerlettermodel',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='offer_expire',
            field=models.DateField(blank=True, null=True),
        )
        
    ]
