# Generated by Django 5.0.3 on 2024-08-29 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0138_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='WishNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('wish_message', models.TextField(blank=True, null=True)),
                ('wished_emps', models.ManyToManyField(blank=True, null=True, to='HRM_App.employeedatamodel')),
                ('wishes_to_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes_to_emp', to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
