# Generated by Django 5.0.3 on 2024-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0139_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        )
    ]
