# Generated by Django 5.0.3 on 2024-09-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0140_candidateapplicationmodel_appling_for_and_more'),
    ]

    
