# Generated by Django 5.0.3 on 2024-09-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0142_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='secondary_email',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='secondary_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        )
        
    ]
