# Generated by Django 5.0.3 on 2024-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0143_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='employeeinformation',
            name='wish_mail',
            field=models.BooleanField(default=False),
        )
    ]
