# Generated by Django 5.0.3 on 2024-09-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0145_candidateapplicationmodel_appling_for_and_more'),
    ]

    
   
