# Generated by Django 5.0.3 on 2024-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0148_candidateapplicationmodel_appling_for_and_more'),
    ]

    
