# Generated by Django 5.0.3 on 2024-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0149_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='Appling_for',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Employeement', 'Employeement')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='Referred_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='current_position',
            field=models.CharField(blank=True, choices=[('Experience', 'Experience'), ('Fresher', 'Fresher'), ('Student', 'Student'), ('Consultant', 'Consultant')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='employee_attendance_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='calledcandidatesmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('interview_scheduled', 'Interview_Scheduled'), ('rejected', 'Rejected'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('to_client', 'Consider_to_Client')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Final_Results',
            field=models.CharField(blank=True, choices=[('consider_to_client', 'consider to client'), ('Internal_Hiring', 'Internal Hiring'), ('Reject', 'Reject'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('Pending', 'Pending'), ('On_Hold', 'OnHold'), ('offered', 'Offered'), ('Offer_did_not_accept', "Offer did't accept"), ('walkout', 'Walkout')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='JobPortalSource',
            field=models.CharField(blank=True, choices=[('naukri', 'Naukri'), ('linkedin', 'Linkedin'), ('foundit', 'Foundit'), ('referral', 'Referral'), ('direct', 'Direct'), ('indeed', 'Indeed'), ('others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hrfinalstatusmodel',
            name='Final_Result',
            field=models.CharField(blank=True, choices=[('consider_to_client', 'Consider_to_Client'), ('Internal_Hiring', 'Internal Hiring'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('Reject', 'Reject'), ('On_Hold', 'On Hold'), ('Pending', 'Pending'), ('Offer_did_not_accept', "Offer did't accept")], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='InterviewRoundName',
            field=models.CharField(choices=[('technical_round', 'Technical_Round'), ('manager_round', 'Manager_Round'), ('hr_round', 'HR_Round'), ('ceo_round', 'CEO_Round')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='Screening_Status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled For Next Round'), ('rejected', 'Rejected'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('to_client', 'Scheduled Interview to Client'), ('walkout', 'Walkout')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='interview_Status',
            field=models.CharField(blank=True, choices=[('consider_to_client', 'Consider to Client'), ('Internal_Hiring', 'Internal Hiring'), ('Reject', 'Reject'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('On_Hold', 'On Hold'), ('Offer_did_not_accept', "Offer did't accept")], max_length=100, null=True),
        ),
    ]
