# Generated by Django 5.0.3 on 2024-11-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0150_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplicationmodel',
            name='Referred_by',
        ),
    ]
