# Generated by Django 5.0.3 on 2024-11-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0151_remove_candidateapplicationmodel_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplicationmodel',
            name='Referred_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
