# Generated by Django 5.0.3 on 2024-11-10 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0152_candidateapplicationmodel_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_number', models.IntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='source_of_hire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('genderqueer', 'Genderqueer'), ('genderfluid', 'Genderfluid'), ('agender', 'Agender'), ('bigender', 'Bigender'), ('transgender', 'Transgender'), ('intersex', 'Intersex'), ('demiboy', 'Demiboy'), ('demigirl', 'Demigirl'), ('demigender', 'Demigender'), ('two_spirit', 'Two-Spirit'), ('butch', 'Butch'), ('binary_gender', 'Binary Gender'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('group_chat', 'Group Chat'), ('one_to_one_chat', 'One-to-One Chat')], max_length=15)),
                ('chat_message', models.TextField()),
                ('current_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='HRM_App.employeeinformation')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to='HRM_App.employeeinformation')),
                ('to_group_of_emp', models.ManyToManyField(blank=True, related_name='group_chats', to='HRM_App.employeeinformation')),
            ],
        ),
    ]
