# Generated by Django 5.0.3 on 2024-11-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0153_employeeidtracker_employeeinformation_source_of_hire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
