# Generated by Django 5.0.3 on 2024-11-28 05:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0154_offerlettermodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(choices=[('interview_calls', 'Interview Calls'), ('job_posts', 'Job Posts'), ('client_calls', 'Client Calls')], max_length=1000)),
                ('desctiption', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_assigned_Date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('targets', models.IntegerField(blank=True, null=True)),
                ('Achived_target', models.IntegerField(default=0)),
                ('Activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.activitylistmodel')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='HRM_App.employeedatamodel')),
                ('activity_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_from', to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='MonthAchivesListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.IntegerField(blank=True, default=0, null=True)),
                ('Date', models.DateField(default=django.utils.timezone.localdate)),
                ('Activity_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.newactivitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='NewDailyAchivesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('job_post_remarks', models.TextField(blank=True, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_email', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_location', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_current_status', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('experience', 'Experience')], max_length=100, null=True)),
                ('candidate_experience', models.IntegerField(blank=True, null=True)),
                ('interview_status', models.CharField(blank=True, choices=[('call_notpicked', 'Call Not Picked'), ('dis_connect', 'Disconnect'), ('will_revert_back', 'Will Revert Back'), ('interview_scheduled', 'Interview_Scheduled'), ('walkin', 'walkin'), ('rejected', 'Rejected'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('to_client', 'Consider_to_Client'), ('offer', 'Offer')], max_length=100, null=True)),
                ('message_to_candidates', models.TextField(blank=True, null=True)),
                ('interview_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('interview_walkin_date', models.DateTimeField(blank=True, null=True)),
                ('interview_call_remarks', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('client_enquire_purpose', models.CharField(blank=True, max_length=1500, null=True)),
                ('client_spok', models.CharField(blank=True, max_length=1500, null=True)),
                ('client_status', models.CharField(blank=True, choices=[('job', 'Job'), ('closed', 'Closed'), ('followup', 'FollowUp')], max_length=100, null=True)),
                ('client_call_remarks', models.TextField(blank=True, null=True)),
                ('current_day_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.monthachiveslistmodel')),
            ],
        ),
    ]
