# Generated by Django 5.0.3 on 2024-11-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0155_activitylistmodel_newactivitymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamodel',
            name='all_employees_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='all_employees_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='assign_leave_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='assign_offerletter_prepare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='assign_resignation_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='attendance_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='employee_personal_details_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='holiday_calender_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='job_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='leave_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='leave_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='massmail_communication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='salary_component_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='salary_template_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedatamodel',
            name='self_activity_add',
            field=models.BooleanField(default=False),
        ),
    ]
