# Generated by Django 5.0.3 on 2024-12-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0156_employeedatamodel_all_employees_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='Policies_NDA_Accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='bd_wish_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='consultant_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='consultant_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='notice_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='salutation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='work_location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Final_Results',
            field=models.CharField(blank=True, choices=[('consider_to_client', 'consider to client'), ('Internal_Hiring', 'Internal Hiring'), ('Reject', 'Reject'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('Pending', 'Pending'), ('On_Hold', 'OnHold'), ('offered', 'Offered'), ('Offer_did_not_accept', "Offer did't accept"), ('walkout', 'Walkout'), ('client_offered', 'client_offered'), ('candidate_joined', 'candidate_joined')], default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='Employeement_Type',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('permanent', 'permanent'), ('Trainee', 'Trainee'), ('Consultant', 'Consultant')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('in_active', 'In_Active'), ('Resigned', 'Resigned')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
