# Generated by Django 5.0.3 on 2025-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0159_alter_hrfinalstatusmodel_final_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='WFH_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='from_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='latitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='longitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='to_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
