# Generated by Django 5.0.3 on 2025-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0160_employeeinformation_wfh_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='DOJ',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='candidate_for',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('experience', 'Experience')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='current_ctc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='expected_ctc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='have_laptop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='industries_worked',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
