# Generated by Django 5.0.3 on 2025-05-03 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0001_initial'),
        ('HRM_App', '0161_newdailyachivesmodel_doj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrfinalstatusmodel',
            name='req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.requirement'),
        ),
        migrations.AddField(
            model_name='interviewschedulmodel',
            name='for_whome',
            field=models.CharField(blank=True, choices=[('client', 'client'), ('ours', 'ours')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hrfinalstatusmodel',
            name='Final_Result',
            field=models.CharField(blank=True, choices=[('consider_to_client', 'Consider_to_Client'), ('Internal_Hiring', 'Internal Hiring'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('Reject', 'Reject'), ('On_Hold', 'On Hold'), ('walkout', 'Walkout'), ('Pending', 'Pending'), ('Offer_did_not_accept', "Offer did't accept"), ('client_rejected', 'client_rejected'), ('client_offered', 'client_offered'), ('client_kept_on_hold', 'client_kept_on_hold'), ('client_offer_rejected', 'client_offer_rejected'), ('candidate_joined', 'candidate_joined')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedulmodel',
            name='InterviewRoundName',
            field=models.CharField(choices=[('technical_round', 'Technical_Round'), ('manager_round', 'Manager_Round'), ('hr_round', 'HR_Round'), ('ceo_round', 'CEO_Round')], default='hr_round', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='Screening_Status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled For Next Round'), ('rejected', 'Rejected'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('to_client', 'Scheduled Interview to Client'), ('walkout', 'Walkout')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='interview_Status',
            field=models.CharField(blank=True, choices=[('consider_to_client', 'Consider to Client'), ('Internal_Hiring', 'Internal Hiring'), ('Reject', 'Reject'), ('Rejected_by_Candidate', 'Rejected_by_Candidate'), ('On_Hold', 'On Hold'), ('Offer_did_not_accept', "Offer did't accept"), ('client_rejected', 'client_rejected'), ('client_offered', 'client_offered'), ('client_kept_on_hold', 'client_kept_on_hold'), ('client_offer_rejected', 'client_offer_rejected'), ('candidate_joined', 'candidate_joined')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RequirementAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('position_count', models.IntegerField(blank=True, default=0, null=True)),
                ('closed_pos_count', models.IntegerField(blank=True, default=0, null=True)),
                ('assigned_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='HRM_App.employeedatamodel')),
                ('assigned_to_recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recruiter', to='HRM_App.employeedatamodel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.ourclients')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='interviewschedulmodel',
            name='assigned_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.requirementassign'),
        ),
    ]
