# Generated by Django 5.0.3 on 2025-05-03 11:08

import HRM_App.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0001_initial'),
        ('HRM_App', '0162_hrfinalstatusmodel_req_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCandidateJoiningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('CTC', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('commisition_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_invoice_created', models.BooleanField(default=False)),
                ('is_joined', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.candidateapplicationmodel')),
                ('client_interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.interviewschedulmodel')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=HRM_App.models.invoice_num_id, max_length=50, unique=True)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commisition_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('generated_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('joined_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.clientcandidatejoininghistory')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPaymentent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=500, null=True)),
                ('utr', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('responseCode', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('accountType', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('generated_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.client_invoice')),
            ],
        ),
    ]
