# Generated by Django 5.0.3 on 2025-05-03 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Emp_App', '0001_initial'),
        ('HRM_App', '0163_clientcandidatejoininghistory_client_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.ourclients')),
                ('client_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.newdailyachivesmodel')),
            ],
        ),
    ]
