# Generated by Django 5.2.3 on 2025-06-13 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0164_clientservicesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishnotifications',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='wishnotifications',
            name='is_activate',
        ),
        migrations.AddField(
            model_name='wishnotifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wish_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wished_emps',
            field=models.ManyToManyField(related_name='wish_notifications', to='HRM_App.employeedatamodel'),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wishes_to_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel'),
        ),
    ]
