# Generated by Django 5.2.3 on 2025-06-13 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0165_remove_wishnotifications_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishnotifications',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wishnotifications',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddField(
            model_name='wishnotifications',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wish_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wished_emps',
            field=models.ManyToManyField(blank=True, null=True, to='HRM_App.employeedatamodel'),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wishes_to_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes_to_emp', to='HRM_App.employeedatamodel'),
        ),
    ]
