# Generated by Django 5.2.3 on 2025-06-14 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0166_remove_wishnotifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishnotifications',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wish_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wished_emps',
            field=models.ManyToManyField(related_name='wish_notifications', to='HRM_App.employeedatamodel'),
        ),
        migrations.AlterField(
            model_name='wishnotifications',
            name='wishes_to_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel'),
        ),
    ]
