# Generated by Django 5.2.8 on 2025-11-24 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0167_alter_wishnotifications_created_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, help_text='e.g., Technology, Finance, Healthcare', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Python, Django, React, Project Management', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='Offered_Instance',
            field=models.ManyToManyField(blank=True, to='HRM_App.offerlettermodel'),
        ),
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='candidate_for',
            field=models.CharField(blank=True, choices=[('OJT', 'OJT'), ('Internal_Hiring', 'Internal_Hiring')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(help_text="e.g., 'New York, NY', 'Remote'", max_length=255)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('vacancies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='e.g., USD, EUR, INR', max_length=5)),
                ('salary_type', models.CharField(choices=[('YEARLY', 'Per Year'), ('MONTHLY', 'Per Month'), ('HOURLY', 'Per Hour')], default='YEARLY', max_length=10)),
                ('experience_required_min_years', models.PositiveIntegerField(default=0)),
                ('experience_required_max_years', models.PositiveIntegerField(blank=True, null=True)),
                ('education_required', models.CharField(choices=[('ANY', 'Any'), ('HIGH_SCHOOL', 'High School'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('PHD', 'PhD')], default='ANY', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the job from students/public API')),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='HRM_App.company')),
                ('posted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
                ('skills_required', models.ManyToManyField(blank=True, related_name='job_postings', to='HRM_App.skill')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
