# Generated by Django 5.2.8 on 2025-11-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0168_company_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='not_type',
            field=models.CharField(blank=True, choices=[('cal', 'cal'), ('scr_assign', 'scr_assign'), ('int_assign', 'int_assign'), ('scr_com', 'scr_com'), ('int_com', 'int_com'), ('task_assign', 'task_assign')], max_length=100, null=True),
        ),
    ]
