# Generated by Django 5.2.8 on 2025-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0169_alter_notification_not_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
