# Generated by Django 5.2.8 on 2025-12-23 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0170_notification_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='AppliedDate',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='AppliedDesignation',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='DataOfApplied',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='Filled_by',
            field=models.CharField(blank=True, db_index=True, default='Candidate', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplicationmodel',
            name='JobPortalSource',
            field=models.CharField(blank=True, choices=[('naukri', 'Naukri'), ('linkedin', 'Linkedin'), ('foundit', 'Foundit'), ('referral', 'Referral'), ('direct', 'Direct'), ('indeed', 'Indeed'), ('others', 'Others')], db_index=True, max_length=100, null=True),
        ),
    ]
