# Generated by Django 5.2.8 on 2026-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0171_alter_candidateapplicationmodel_applieddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
