# Generated by Django 5.2.8 on 2026-01-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0172_alter_newdailyachivesmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='joining_form_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='joining_form_filled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='joining_form_resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='joining_form_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerlettermodel',
            name='manual_offer_sent',
            field=models.BooleanField(default=False),
        ),
    ]
