# Generated by Django 5.2.8 on 2026-01-28 04:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0173_offerlettermodel_joining_form_filled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='closure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('follow_up', 'Follow Up'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='active', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='rejection_type',
            field=models.CharField(blank=True, choices=[('emp_rejected', 'Employee Rejected'), ('candidate_rejected', 'Candidate Rejected')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='FollowUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('interview', 'Interview'), ('client', 'Client')], help_text='Type of follow-up: interview or client call', max_length=20)),
                ('expected_date', models.DateField(help_text='Expected date to follow up')),
                ('expected_time', models.TimeField(help_text='Expected time to follow up')),
                ('notes', models.TextField(blank=True, help_text='Follow-up notes or instructions', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Current status of the follow-up', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.localtime, help_text='When the follow-up was created')),
                ('completed_on', models.DateTimeField(blank=True, help_text='When the follow-up was marked as completed', null=True)),
                ('activity_record', models.ForeignKey(help_text='Reference to the activity record being followed up', on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='HRM_App.newdailyachivesmodel')),
                ('created_by', models.ForeignKey(help_text='Employee who created this follow-up', on_delete=django.db.models.deletion.CASCADE, related_name='created_followups', to='HRM_App.employeedatamodel')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['-created_on'],
            },
        ),
    ]
