# Generated by Django 5.2.8 on 2026-01-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0174_newdailyachivesmodel_closure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newdailyachivesmodel',
            name='client_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newdailyachivesmodel',
            name='client_status',
            field=models.CharField(blank=True, choices=[('job', 'Job'), ('converted_to_client', 'Converted to Client'), ('closed', 'Closed'), ('followup', 'FollowUp')], max_length=100, null=True),
        ),
    ]
