# Generated by Django 5.2.7 on 2026-02-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0175_newdailyachivesmodel_client_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DAS Auth Code',
                'verbose_name_plural': 'DAS Auth Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
