# Generated by Django 5.0.3 on 2025-05-03 10:20

import Contract_Emp_App.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default=Contract_Emp_App.models.client_id, max_length=255, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternative_emails', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('client_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_proof', models.FileField(blank=True, null=True, upload_to='client_documents')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.ourclients')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('open_positions', models.IntegerField(blank=True, default=0, null=True)),
                ('hiring_start_date', models.DateField(blank=True, null=True)),
                ('hiring_end_date', models.DateField(blank=True, null=True)),
                ('package_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_min', models.IntegerField(blank=True, null=True)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('added_by', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contract_Emp_App.ourclients')),
            ],
        ),
    ]
