# Generated by Django 5.0.3 on 2024-05-08 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0001_initial'),
        ('HRM_App', '0007_rename_designation_employeedatamodel_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformation',
            name='Designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.designationmodel'),
        ),
    ]
