# Generated by Django 5.0.3 on 2024-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0002_employeeinformation_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='Designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
