# Generated by Django 5.0.3 on 2024-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0003_alter_employeeinformation_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformation',
            name='height',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformation',
            name='weight',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
