# Generated by Django 5.0.3 on 2024-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0005_remove_aditionalinformationmodel_candidate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetails',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='relation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
