# Generated by Django 5.0.3 on 2024-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0006_alter_familydetails_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatereference',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='Diabetics',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='allergic_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='blood_pessure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='other_illness',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='place_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
