# Generated by Django 5.0.3 on 2024-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0007_alter_candidatereference_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='appointment_letter',
        ),
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='degree_cirtificates',
        ),
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='passport_size_photograph',
        ),
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='permanent_address_proff',
        ),
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='present_address_proff',
        ),
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='relieving_letter',
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='Attachement_cirtificates',
            field=models.FileField(blank=True, upload_to='cirtificates_folder/'),
        ),
    ]
