# Generated by Django 5.0.3 on 2024-05-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0008_remove_attachmentsmodel_appointment_letter_and_more'),
        ('HRM_App', '0017_employeeinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='exceperiencemodel',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='last_position_held',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='aditionalinformationmodel',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='employeeidentity',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation'),
        ),
        migrations.DeleteModel(
            name='EmployeeInformation',
        ),
    ]
