# Generated by Django 5.0.3 on 2024-05-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0009_alter_bankaccountdetails_emp_information_and_more'),
        ('HRM_App', '0017_employeeinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('serial_no', models.CharField(max_length=20, unique=True)),
                ('company_policy_category', models.CharField(choices=[('Category1', 'Category 1')], max_length=20)),
                ('upload_file', models.FileField(upload_to='policy_files/')),
                ('applicable_employees', models.ManyToManyField(related_name='applicable_policies', to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
