# Generated by Django 5.0.3 on 2024-05-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0010_companypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='company_policy_category',
            field=models.CharField(blank=True, choices=[('Category1', 'Category 1')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='serial_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='policy_files/'),
        ),
    ]
