# Generated by Django 5.0.3 on 2024-05-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0011_alter_companypolicy_company_policy_category_and_more'),
        ('HRM_App', '0017_employeeinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='applicable_employees',
            field=models.ManyToManyField(blank=True, related_name='applicable_policies', to='HRM_App.employeedatamodel'),
        ),
    ]
