# Generated by Django 5.0.3 on 2024-05-16 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0012_alter_companypolicy_applicable_employees'),
        ('HRM_App', '0018_rename_date_activity_activity_added_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('resigned_letter_file', models.FileField(blank=True, null=True, upload_to='resignation_letters/')),
                ('resignation_verification', models.CharField(blank=True, choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elemployee', to='HRM_App.employeedatamodel')),
                ('reporting_manager_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
