# Generated by Django 5.0.3 on 2024-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0013_resignationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
