# Generated by Django 5.0.3 on 2024-05-17 04:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0014_resignationmodel_remarks'),
        ('HRM_App', '0018_rename_date_activity_activity_added_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Of_Interview', models.DateField(blank=True, null=True)),
                ('Interviewed_On', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('Interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('resignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.resignationmodel')),
            ],
        ),
    ]
