# Generated by Django 5.0.3 on 2024-05-17 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0015_exitinterviewmodel'),
        ('HRM_App', '0020_employeedatamodel_reporting_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='HR_manager_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HR', to='HRM_App.employeedatamodel'),
        ),
        migrations.CreateModel(
            name='ExitDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Leave', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('SettledOn', models.DateField(blank=True, null=True)),
                ('EmpLeftOrganization', models.BooleanField(default=False)),
                ('NoticedServed', models.BooleanField(default=False)),
                ('FitToBeRehired', models.BooleanField(default=False)),
                ('AlternateEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('AlternateMobile', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.exitinterviewmodel')),
            ],
        ),
    ]
