# Generated by Django 5.0.3 on 2024-05-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0016_resignationmodel_hr_manager_name_exitdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='is_rm_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
