# Generated by Django 5.0.3 on 2024-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0017_resignationmodel_is_rm_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='hr_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='is_hr_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='rm_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
