# Generated by Django 5.0.3 on 2024-05-18 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0018_resignationmodel_hr_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='Applied_On',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='Date_Of_Interview',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='hr_verified_On',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='rm_verified_On',
            field=models.DateField(blank=True, null=True),
        ),
    ]
