# Generated by Django 5.0.3 on 2024-05-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0019_resignationmodel_applied_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='resignation_verification',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('declined', 'Declined')], default='declined', max_length=100, null=True),
        ),
    ]
