# Generated by Django 5.0.3 on 2024-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0020_alter_resignationmodel_resignation_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='is_hr_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='is_rm_verified',
            field=models.BooleanField(default=False),
        ),
    ]
