# Generated by Django 5.0.3 on 2024-05-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0021_alter_resignationmodel_is_hr_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='resignation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.resignationmodel'),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='resignation_verification',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=100, null=True),
        ),
    ]
