# Generated by Django 5.0.3 on 2024-05-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0022_exitdetailsmodel_resignation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='exit_interview',
        ),
    ]
