# Generated by Django 5.0.3 on 2024-05-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0023_remove_exitdetailsmodel_exit_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitinterviewmodel',
            name='Interviewer',
        ),
        migrations.RemoveField(
            model_name='exitinterviewmodel',
            name='resignation',
        ),
        migrations.DeleteModel(
            name='ExitDetailsModel',
        ),
        migrations.DeleteModel(
            name='ExitInterviewModel',
        ),
    ]
