# Generated by Django 5.0.3 on 2024-05-19 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0024_remove_exitinterviewmodel_interviewer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days_to_Serve_Notice', models.IntegerField(blank=True, null=True)),
                ('notice_period_agrry', models.BooleanField(default=False)),
                ('compantation', models.IntegerField(blank=True, null=True)),
                ('compantation_pay_agrry', models.BooleanField(default=False)),
                ('Date_to_Leave', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('FitToBeRehired', models.BooleanField(default=False)),
                ('AlternateEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('AlternateMobile', models.CharField(blank=True, max_length=100, null=True)),
                ('NoticedServed', models.BooleanField(default=False)),
                ('SettledOn', models.DateField(blank=True, null=True)),
                ('EmpLeftOrganization', models.BooleanField(default=False)),
                ('Date_of_Left_Organization', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('resignation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.resignationmodel')),
            ],
        ),
    ]
