# Generated by Django 5.0.3 on 2024-05-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0025_exitdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidatereference',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatereference',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencydetails',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencydetails',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeeducation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeidentity',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeidentity',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeepersonalinformation',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepersonalinformation',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exceperiencemodel',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceperiencemodel',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='last_position_held',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='last_position_held',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pfdetails',
            name='is_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pfdetails',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
