# Generated by Django 5.0.3 on 2024-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0026_aditionalinformationmodel_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='Required_letters',
            field=models.FileField(blank=True, upload_to='Resignation_Certificates'),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='is_required_letters_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='required_letters_taken_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
