# Generated by Django 5.0.3 on 2024-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0027_exitdetailsmodel_required_letters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='compantation',
        ),
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='compantation_pay_agrry',
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='compensation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='compensation_pay_agrry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aditionalinformationmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatereference',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeidentity',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exceperiencemodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='last_position_held',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
