# Generated by Django 5.0.3 on 2024-05-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0028_remove_exitdetailsmodel_compantation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exitdetailsmodel',
            unique_together={('resignation',)},
        ),
    ]
