# Generated by Django 5.0.3 on 2024-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0029_alter_exitdetailsmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
