# Generated by Django 5.0.3 on 2024-05-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0030_exitdetailsmodel_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='TotalSettlement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
