# Generated by Django 5.0.3 on 2024-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0031_exitdetailsmodel_totalsettlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='place_of_birth',
            field=models.CharField(max_length=100),
        ),
    ]
