# Generated by Django 5.0.3 on 2024-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0032_alter_employeepersonalinformation_place_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfdetails',
            name='allow_epf_excess_contribution',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='allow_eps_excess_contribution',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='family_pf_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='is_existing_number_of_eps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='pf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='pf_join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pfdetails',
            name='uan',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
