# Generated by Django 5.0.3 on 2024-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0033_alter_pfdetails_allow_epf_excess_contribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='Attachement_cirtificates',
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='address_proof',
            field=models.FileField(blank=True, upload_to='address_proof/'),
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='upload_photo',
            field=models.ImageField(blank=True, upload_to='employee_images/'),
        ),
    ]
