# Generated by Django 5.0.3 on 2024-05-29 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0034_remove_attachmentsmodel_attachement_cirtificates_and_more'),
        ('HRM_App', '0043_alter_employeedatamodel_employeeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permission_Name', models.CharField(max_length=100, blank=True,null=True, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Added_Date', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
        migrations.CreateModel(
            name='Employees_Under_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valid_From', models.DateTimeField(blank=True, null=True)),
                ('Valid_To', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_of_assigned', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('PermissionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS_App.employeepermissionsmodel')),
                ('Permission_To_Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
