# Generated by Django 5.0.3 on 2024-06-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0035_employeepermissionsmodel_employees_under_permission'),
        ('HRM_App', '0054_alter_dailyachives_achieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='elemployee', to='HRM_App.employeedatamodel'),
        ),
    ]
