# Generated by Django 5.0.3 on 2024-06-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0036_alter_resignationmodel_employee_id'),
        ('HRM_App', '0060_alter_candidateapplicationmodel_final_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elemployee', to='HRM_App.employeedatamodel'),
        ),
    ]
