# Generated by Django 5.0.3 on 2024-06-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0037_alter_resignationmodel_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_under_permission',
            name='PermissionName',
        ),
        migrations.RemoveField(
            model_name='employees_under_permission',
            name='Permission_To_Emp',
        ),
        migrations.DeleteModel(
            name='EmployeePermissionsModel',
        ),
        migrations.DeleteModel(
            name='Employees_Under_Permission',
        ),
    ]
