# Generated by Django 5.0.3 on 2024-07-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0038_remove_employees_under_permission_permissionname_and_more'),
        ('HRM_App', '0101_alter_employeeweekoffs_model_weekoffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualCTC', models.IntegerField()),
                ('MonthlyCTC', models.IntegerField()),
                ('EMP_Information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation')),
            ],
        ),
    ]
