# Generated by Django 5.0.3 on 2024-07-08 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0039_employeesalarymodel'),
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('esi', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
                ('profession_tax', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('uan_number', models.CharField(max_length=50)),
                ('pf_number', models.CharField(max_length=50)),
                ('total_working_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leaves_taken', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lop_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('designation', models.CharField(max_length=50)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AllowanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('allowance', 'Allowance'), ('deduction', 'Deduction')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EMS_App.payslip')),
            ],
        ),
    ]
