# Generated by Django 5.0.3 on 2024-07-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0040_deductions_payslip_allowancededuction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReligionModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion_name', models.CharField(max_length=100)),
            ],
        ),
    ]
