# Generated by Django 5.0.3 on 2024-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0041_religionmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonalinformation',
            name='religion',
        ),
    ]
