# Generated by Django 5.0.3 on 2024-07-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0042_remove_employeepersonalinformation_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalinformation',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.religionmodels'),
        ),
    ]
