# Generated by Django 5.0.3 on 2024-07-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0043_employeepersonalinformation_religion'),
        ('HRM_App', '0126_remove_employeeinformation_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergic_to', models.CharField(blank=True, max_length=1000)),
                ('blood_group', models.CharField(blank=True, max_length=100)),
                ('blood_presure', models.CharField(blank=True, max_length=100)),
                ('Diabetics', models.CharField(blank=True, max_length=100)),
                ('decleration', models.BooleanField(default=False)),
                ('other_illness', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('EMP_Information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation')),
            ],
        ),
    ]
