# Generated by Django 5.0.3 on 2024-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0044_medicaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydetails',
            name='decleration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencydetails',
            name='other_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MedicalDetails',
        ),
    ]
