# Generated by Django 5.0.3 on 2024-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0045_emergencydetails_decleration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aditionalinformationmodel',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='aditionalinformationmodel',
            name='three_principles',
        ),
        migrations.RemoveField(
            model_name='aditionalinformationmodel',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='strengths1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='strengths2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='strengths3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='three_principles1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='three_principles2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='three_principles3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='weaknesses1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='weaknesses2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aditionalinformationmodel',
            name='weaknesses3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aditionalinformationmodel',
            name='in_abroad',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='aditionalinformationmodel',
            name='in_india',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'No')], max_length=100),
        ),
    ]
