# Generated by Django 5.0.3 on 2024-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0046_remove_aditionalinformationmodel_strengths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentsmodel',
            name='address_proof',
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='Degree_mark_sheets',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/Degree_mark_sheets/'),
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='Offer_letter_copy',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/Offer_letter_copy/'),
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='permenent_address_proof',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/address_proof/'),
        ),
        migrations.AddField(
            model_name='attachmentsmodel',
            name='present_address_proof',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/present_address_proof/'),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='upload_photo',
            field=models.ImageField(blank=True, upload_to='EmployeeDocuments/employee_images/'),
        ),
    ]
