# Generated by Django 5.0.3 on 2024-07-23 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0047_remove_attachmentsmodel_address_proof_and_more'),
        ('HRM_App', '0126_remove_employeeinformation_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.designationmodel')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
            options={
                'verbose_name_plural': 'Employee Position Histories',
                'ordering': ['-start_date'],
            },
        ),
    ]
