# Generated by Django 5.0.3 on 2024-07-23 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0048_employeepositionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepositionhistory',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
