# Generated by Django 5.0.3 on 2024-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0049_alter_employeepositionhistory_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatereference',
            name='pincode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
