# Generated by Django 5.0.3 on 2024-07-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0051_last_position_held_da_alter_last_position_held_hra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='last_position_held',
            name='non_cash_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
