# Generated by Django 5.0.3 on 2024-07-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0053_last_position_held_non_cash_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeidentity',
            name='pan_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
