# Generated by Django 5.0.3 on 2024-07-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0054_alter_employeeidentity_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='account_proof',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/accoun_folder/'),
        ),
        migrations.AlterField(
            model_name='employeeidentity',
            name='aadher_proof',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/aadher_folder/'),
        ),
        migrations.AlterField(
            model_name='employeeidentity',
            name='pan_proof',
            field=models.FileField(blank=True, upload_to='EmployeeDocuments/pancard_folder/'),
        ),
    ]
