# Generated by Django 5.0.3 on 2024-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0055_alter_bankaccountdetails_account_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='branch_address',
            field=models.TextField(blank=True),
        ),
    ]
