# Generated by Django 5.0.3 on 2024-07-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0056_bankaccountdetails_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountdetails',
            name='branch',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
