# Generated by Django 5.0.3 on 2024-07-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0057_alter_bankaccountdetails_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentsmodel',
            old_name='permenent_address_proof',
            new_name='permanent_address_proof',
        ),
    ]
