# Generated by Django 5.0.3 on 2024-07-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0058_rename_permenent_address_proof_attachmentsmodel_permanent_address_proof'),
        ('HRM_App', '0126_remove_employeeinformation_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_Submited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.CharField(blank=True, max_length=100)),
                ('submited', models.BooleanField(default=False)),
                ('submited_date', models.DateField(blank=True)),
                ('will_submit_date', models.DateField(blank=True)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('EMP_Information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation')),
            ],
        ),
    ]
