# Generated by Django 5.0.3 on 2024-07-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0059_documents_submited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents_submited',
            name='place',
        ),
    ]
