# Generated by Django 5.0.3 on 2024-07-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0060_remove_documents_submited_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents_submited',
            old_name='submited',
            new_name='submitted',
        ),
        migrations.RenameField(
            model_name='documents_submited',
            old_name='submited_date',
            new_name='submitted_date',
        ),
    ]
