# Generated by Django 5.0.3 on 2024-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0061_rename_submited_documents_submited_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_submited',
            name='submitted_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
