# Generated by Django 5.0.3 on 2024-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0062_alter_documents_submited_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_submited',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents_submited',
            name='will_submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
