# Generated by Django 5.0.3 on 2024-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0063_alter_documents_submited_submitted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
