# Generated by Django 5.0.3 on 2024-07-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0064_declaration_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='signature',
            field=models.ImageField(blank=True, upload_to='EmployeeDocuments/Signature/'),
        ),
    ]
