# Generated by Django 5.0.3 on 2024-07-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0065_alter_declaration_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='international_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='physically_challenged',
            field=models.BooleanField(default=True),
        ),
    ]
