# Generated by Django 5.0.3 on 2024-07-25 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0066_alter_employeepersonalinformation_international_employee_and_more'),
        ('HRM_App', '0130_employeedatamodel_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMassMailsSendedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mail_attachments/')),
                ('maill_sended_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('employees_list', models.ManyToManyField(blank=True, null=True, to='HRM_App.employeedatamodel')),
                ('mail_sended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_sended_by', to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
