# Generated by Django 5.0.3 on 2024-07-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0067_companymassmailssendedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePositionHistory',
        ),
    ]
