# Generated by Django 5.0.3 on 2024-07-27 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0068_delete_employeepositionhistory'),
        ('HRM_App', '0130_employeedatamodel_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployeesPositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('das_position', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('reason_for_change', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('employment_type', models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], max_length=50, null=True)),
                ('assigned_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_changes', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.designationmodel')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('rm_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_manager', to='HRM_App.employeedatamodel')),
            ],
            options={
                'verbose_name_plural': 'Employee Position Histories',
                'ordering': ['-start_date'],
            },
        ),
    ]
