# Generated by Django 5.0.3 on 2024-07-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0069_companyemployeespositionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyemployeespositionhistory',
            name='employment_type',
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='Employeement_Type',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('permanent', 'permanent')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='internship_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='internship_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='probation_Duration_From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='probation_Duration_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='probation_status',
            field=models.CharField(blank=True, choices=[('probationer', 'Probationer'), ('confirmed', 'Confirmed')], max_length=100, null=True),
        ),
    ]
