# Generated by Django 5.0.3 on 2024-08-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0070_remove_companyemployeespositionhistory_employment_type_and_more'),
        ('HRM_App', '0135_candidateapplicationmodel_appling_for_and_more'),
        ('LMS_App', '0104_employeeselfevaluationreviewmodel_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('CEO', models.CharField(max_length=1000)),
                ('Company_Head', models.CharField(max_length=1000)),
                ('Company_logo', models.FileField(blank=True, null=True, upload_to='Company_files/Company_logo/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='companyemployeespositionhistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='aditionalinformationmodel',
            name='passport_num',
        ),
        migrations.RemoveField(
            model_name='aditionalinformationmodel',
            name='validate',
        ),
        migrations.RemoveField(
            model_name='candidatereference',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidatereference',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidatereference',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidatereference',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='candidatereference',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employeepersonalinformation',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='pfdetails',
            name='family_pf_no',
        ),
        migrations.AddField(
            model_name='bankaccountdetails',
            name='Holder_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='Appraisal_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeselfevaluation'),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='applicable_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyemployeespositionhistory',
            name='is_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='landline',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employeeidentity',
            name='passport_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeidentity',
            name='passport_proof',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/passport_folder/'),
        ),
        migrations.AddField(
            model_name='employeeidentity',
            name='validate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='Degree_mark_sheets',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/Degree_mark_sheets/'),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='Offer_letter_copy',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/Offer_letter_copy/'),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='permanent_address_proof',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/address_proof/'),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='present_address_proof',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/present_address_proof/'),
        ),
        migrations.AlterField(
            model_name='attachmentsmodel',
            name='upload_photo',
            field=models.ImageField(blank=True, null=True, upload_to='EmployeeDocuments/employee_images/'),
        ),
        migrations.AlterField(
            model_name='documents_submited',
            name='Document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='international_employee',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='physically_challenged',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='residential_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonalinformation',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalarymodel',
            name='AnnualCTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalarymodel',
            name='EMP_Information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel'),
        ),
        migrations.AlterField(
            model_name='employeesalarymodel',
            name='MonthlyCTC',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
