# Generated by Django 5.0.3 on 2024-09-27 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0071_companyprofile_and_more'),
        ('HRM_App', '0145_candidateapplicationmodel_appling_for_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exitdetailsmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='Company_Loans',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='Other_Recoveries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='Retrenchment_Compensation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='accepted_another_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='achieving_goals_rating',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('verygood', 'Very Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='acknowledgement_receipt',
            field=models.FileField(blank=True, null=True, upload_to='acknowledgement_receipt'),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='additional_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='benefits_rating',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('verygood', 'Very Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='career_goals_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='disliked_about_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='good_place_to_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='got_along_with_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='handed_over_signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='handed_over_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='improvements_for_more_rewarding_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='job_responsibilities_rating',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('verygood', 'Very Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='leave_encashment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='liked_best_about_job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='manager_issue_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='manager_rating',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('verygood', 'Very Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='more_satisfactory_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='new_organization_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='new_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='pay_rating',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('verygood', 'Very Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='poor_place_to_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='salary_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='spoke_with_manager_or_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='supervisor_handling_complaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='work_environment_rating',
            field=models.CharField(blank=True, choices=[('outstanding', 'Outstanding'), ('verygood', 'Very Good'), ('satisfactory', 'Satisfactory'), ('fair', 'Fair'), ('unsatisfactory', 'Unsatisfactory')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='would_have_stayed_if_satisfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='would_rejoin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='Interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviwer', to='HRM_App.employeedatamodel'),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='additional_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Anything else you wish to share with us?'),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='handover_details_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='handover_details_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='handover_details_submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='improve_welfare',
            field=models.TextField(blank=True, null=True, verbose_name='What can the organization do to improve staff welfare?'),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='liked_most',
            field=models.TextField(blank=True, null=True, verbose_name='What did you like the most about the organization?'),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='reason_for_leaving',
            field=models.CharField(blank=True, choices=[('career_growth', 'Career Growth/Better Opportunity'), ('personal_reasons', 'Personal Reasons'), ('health_issues', 'Health Issues'), ('relocation', 'Relocation'), ('higher_education', 'Pursuing Higher Education'), ('high_pay', 'High Pay'), ('Death', 'Death'), ('retirement', 'Retirement'), ('layoff', 'Layoff/Company Downsizing'), ('performance', 'Performance Issues'), ('Dismissed', 'Dismissed'), ('contract_end', 'End of Contract'), ('misconduct', 'Misconduct'), ('job_satisfaction', 'Job Dissatisfaction')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='rejoin_interest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], default='Maybe', max_length=10),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='separation_type',
            field=models.CharField(choices=[('voluntary', 'Voluntary'), ('involuntary', 'Involuntary')], default='voluntary', max_length=20),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='Date_of_Left_Organization',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='resignation_verification',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('declined', 'Declined'), ('pending', 'Pending'), ('completed', 'Completed'), ('ongoing', 'On Going')], default='pending', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AssetsClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Communication_Address', models.TextField(blank=True, null=True)),
                ('desktop_laptop_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=20, null=True)),
                ('accessories_tools_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=20, null=True)),
                ('mobile_sim_uniform_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=20, null=True)),
                ('sim_card_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=20, null=True)),
                ('name_plate_id_card_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=20, null=True)),
                ('stationeries_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=20, null=True)),
                ('dept_head_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('handover_details_received', models.TextField(blank=True, null=True)),
                ('handed_over_to', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_handover_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('handover_signature_date', models.DateField(blank=True, null=True)),
                ('separation_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.exitdetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HandoversDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_from', models.CharField(blank=True, max_length=1000, null=True)),
                ('handover_title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('handover_ak_assigned_date', models.DateField(blank=True, null=True)),
                ('assigned_handover_emp_accept_status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'rejected'), ('pending', 'Pending')], max_length=50, null=True)),
                ('emp_accept_status_reason', models.TextField(blank=True, null=True)),
                ('handover_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50, null=True)),
                ('handover_ak_received_date', models.DateField(blank=True, null=True)),
                ('handover_documents', models.FileField(blank=True, null=True, upload_to='handovers/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS_App.resignationmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='Date_to_Leave',
        ),
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='Required_letters',
        ),
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='is_required_letters_taken',
        ),
        migrations.RemoveField(
            model_name='exitdetailsmodel',
            name='required_letters_taken_date',
        ),
    ]
