# Generated by Django 5.0.3 on 2024-09-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0072_alter_exitdetailsmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='FitToBeRehired',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='accepted_another_position',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='career_goals_met',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='compensation_pay_agrry',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='got_along_with_manager',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='notice_period_agrry',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='spoke_with_manager_or_hr',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='would_rejoin',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='rejoin_interest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10),
        ),
    ]
