# Generated by Django 5.0.3 on 2024-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0073_alter_exitdetailsmodel_fittoberehired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='rejoin_interest',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10, null=True),
        ),
    ]
