# Generated by Django 5.0.3 on 2024-09-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0074_alter_resignationmodel_rejoin_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='accepted_another_position',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
