# Generated by Django 5.0.3 on 2024-09-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0075_alter_exitdetailsmodel_accepted_another_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='EmpLeftOrganization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='FitToBeRehired',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='NoticedServed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='career_goals_met',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='compensation_pay_agrry',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='got_along_with_manager',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='notice_period_agrry',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='spoke_with_manager_or_hr',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exitdetailsmodel',
            name='would_rejoin',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
