# Generated by Django 5.0.3 on 2024-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0076_alter_exitdetailsmodel_empleftorganization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignationmodel',
            name='reason_for_leaving',
            field=models.CharField(blank=True, choices=[('career_growth', 'Career Growth/Better Opportunity'), ('personal_reasons', 'Personal Reasons'), ('health_issues', 'Health Issues'), ('relocation', 'Relocation'), ('higher_education', 'Pursuing Higher Education'), ('high_pay', 'High Pay'), ('Death', 'Death'), ('retirement', 'Retirement'), ('layoff', 'Layoff/Company Downsizing'), ('performance', 'Performance Issues'), ('Dismissed', 'Dismissed'), ('contract_end', 'End of Contract'), ('misconduct', 'Misconduct'), ('job_dissatisfaction', 'Job Dissatisfaction')], max_length=50, null=True),
        ),
    ]
