# Generated by Django 5.0.3 on 2024-12-16 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0077_alter_resignationmodel_reason_for_leaving'),
        ('HRM_App', '0157_employeeinformation_policies_nda_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeidentity',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/passport_folder/'),
        ),
        migrations.AddField(
            model_name='employeeidentity',
            name='voter_id',
            field=models.FileField(blank=True, null=True, upload_to='EmployeeDocuments/passport_folder/'),
        ),
        migrations.AddField(
            model_name='exitdetailsmodel',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='other_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resignationmodel',
            name='reason_for_leaving',
            field=models.CharField(blank=True, choices=[('career_growth', 'Career Growth/Better Opportunity'), ('personal_reasons', 'Personal Reasons'), ('health_issues', 'Health Issues'), ('relocation', 'Relocation'), ('higher_education', 'Pursuing Higher Education'), ('high_pay', 'High Pay'), ('Death', 'Death'), ('retirement', 'Retirement'), ('layoff', 'Layoff/Company Downsizing'), ('performance', 'Performance Issues'), ('Dismissed', 'Dismissed'), ('contract_end', 'End of Contract'), ('misconduct', 'Misconduct'), ('end_of_internship', 'end of internship'), ('job_dissatisfaction', 'Job Dissatisfaction'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeAssetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(blank=True, choices=[('Hardware', 'Hard ware'), ('Software', 'Soft ware')], max_length=20, null=True)),
                ('asset_name', models.CharField(blank=True, choices=[('official_mail_id', 'Official Mail ID'), ('portals', 'Portals'), ('social_media_credentials', 'Social Media Credentials'), ('official_data', 'Official Data'), ('sim_card', 'SIM Card'), ('id_card', 'ID Card'), ('others', 'Others')], max_length=500, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('EMP_Information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeinformation')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
