# Generated by Django 5.0.3 on 2024-07-08 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
    ]

    