# Generated by Django 5.0.3 on 2024-07-27 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRM_App', '0131_employeeinformation_employeement_type_and_more'),
        ('payroll_app', '0001_initial'),
    ]
    
    
    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyype', models.CharField(choices=[('allowance', 'allowance'), ('deduction', 'deduction')], max_length=100)),
                ('type_name', models.CharField(max_length=100)),
                ('earning_type', models.CharField(blank=True, max_length=100, null=True)),
                ('consider_for_epf', models.BooleanField(default=False)),
                ('conside_for_esi', models.BooleanField(default=False)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=1800, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('basic_percentage', models.DecimalField(decimal_places=2, default=40, max_digits=4)),
                ('annual_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('annual_fixed_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_basic', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_fixed_allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_cost_to_company', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_cost_to_company', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('types', models.ManyToManyField(to='payroll_app.allowancetype')),
            ],
        ),
        
    ]

