# Generated by Django 5.0.3 on 2024-07-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0131_employeeinformation_employeement_type_and_more'),
        ('payroll_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryBreakUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('salary_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.salarytemplate')),
            ],
        ),
    ]
