# Generated by Django 5.0.3 on 2024-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_employeesalarybreakup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalaryBreakUp',
        ),
    ]
