# Generated by Django 5.0.3 on 2024-08-09 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0136_candidateapplicationmodel_appling_for_and_more'),
        ('payroll_app', '0005_employeesalarybreakup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowancetype',
            old_name='conside_for_esi',
            new_name='consider_for_esi',
        ),
        migrations.RemoveField(
            model_name='allowancetype',
            name='earning_type',
        ),
        migrations.RemoveField(
            model_name='allowancetype',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='allowancetype',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='allowancetype',
            name='tyype',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='annual_basic',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='annual_ctc',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='annual_fixed_allowance',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='basic_percentage',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='monthly_basic',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='monthly_cost_to_company',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='monthly_fixed_allowances',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='monthly_gross',
        ),
        migrations.RemoveField(
            model_name='salarytemplate',
            name='yearly_cost_to_company',
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='caluculate_on_prorata_basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='caluculate_type',
            field=models.CharField(blank=True, choices=[('Flat_Amount', 'Flat_Amount'), ('Percentage_oF_CTC', 'Percentage_oF_CTC')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='deducting_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='deduction_associate_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='deduction_frequency',
            field=models.CharField(blank=True, choices=[('OneTime', 'OneTime'), ('recurring', 'recurring')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='earning_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='earning_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='emp_contribution_ctc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='epf_type',
            field=models.CharField(blank=True, choices=[('always', 'always'), ('pfwage', 'pfwage')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='name_in_payslip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('Fixed_Pay', 'Fixed_Pay'), ('Variable_Pay', 'Variable_Pay')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='percentage_of_ctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='post_tax_d_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='pre_tax_d_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancetype',
            name='type',
            field=models.CharField(blank=True, choices=[('Earning', 'Earning'), ('Pre_Tax_Deduction', 'Pre_Tax_Deduction'), ('Post_Tax_Deduction', 'Post_Tax_Deduction')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeesalarybreakup',
            name='CTC_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='allowancetype',
            name='fixed_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalarybreakup',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel'),
        ),
        migrations.AlterField(
            model_name='salarytemplate',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='payroll_app.allowancetype'),
        ),
        migrations.CreateModel(
            name='EmployeePaySlips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_working_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('worked_days', models.IntegerField(blank=True, null=True)),
                ('paid_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('leaves_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lop_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_gross_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('salary_breakups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employeesalarybreakup')),
            ],
        ),
    ]
