# Generated by Django 5.0.3 on 2024-09-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_rename_conside_for_esi_allowancetype_consider_for_esi_and_more'),
    ]

    