# Generated by Django 5.0.3 on 2024-09-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_remove_salarytemplate_types'),
    ]

    
