# Generated by Django 5.0.3 on 2024-09-03 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_remove_employeesalarybreakup_salary_template_and_more'),
    ]

    
