# Generated by Django 5.0.3 on 2024-09-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_salarytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalarybreakup',
            name='salary_template',
        ),
    ]
