# Generated by Django 5.0.3 on 2024-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0010_remove_employeesalarybreakup_salary_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryTemplate',
        ),
    ]
