# Generated by Django 5.0.3 on 2024-09-03 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0011_delete_salarytemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('types', models.ManyToManyField(blank=True, null=True, to='payroll_app.allowancetype')),
            ],
        ),
    ]
