# Generated by Django 5.0.3 on 2024-09-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0012_salarytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarytemplate',
            name='types',
        ),
    ]
