# Generated by Django 5.0.3 on 2024-09-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0013_remove_salarytemplate_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarytemplate',
            name='types',
            field=models.ManyToManyField(related_name='typesoftemplates', to='payroll_app.allowancetype'),
        ),
    ]
