# Generated by Django 5.0.3 on 2024-09-12 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0014_salarytemplate_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarybreakup',
            name='salary_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.salarytemplate'),
        ),
    ]
