# Generated by Django 5.0.3 on 2024-09-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0015_employeesalarybreakup_salary_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayslips',
            name='salary_breakups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employeesalarybreakup'),
        ),
    ]
