# Generated by Django 5.0.3 on 2024-09-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0016_alter_employeepayslips_salary_breakups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayslips',
            name='worked_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
