# Generated by Django 5.0.3 on 2025-02-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0017_alter_employeepayslips_worked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayslips',
            name='public_holidays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeepayslips',
            name='week_off_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
