# Generated by Django 5.0.3 on 2024-06-15 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HRM_App', '0077_rename_spousedesignation_review_spousename'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesTypeDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Of_leaves', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLeaveApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sick_leave', models.BooleanField(blank=True, default=False, null=True)),
                ('is_annual_leave', models.BooleanField(blank=True, default=False, null=True)),
                ('is_casual_leave', models.BooleanField(blank=True, default=False, null=True)),
                ('unpaid_leaves', models.BooleanField(blank=True, default=False, null=True)),
                ('Compensatory_Off', models.BooleanField(blank=True, default=False, null=True)),
                ('Loss_Off_Pay', models.BooleanField(blank=True, default=False, null=True)),
                ('EmployeeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='CasualLeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Casual_Leaves', models.IntegerField(blank=True, default=1, null=True)),
                ('utilised_leaves', models.IntegerField(blank=True, default=0, null=True)),
                ('carried_forward_leaves', models.IntegerField(blank=True, default=0, null=True)),
                ('in_mbl', models.IntegerField(blank=True, default=1, null=True)),
                ('Year', models.DateField(blank=True, null=True)),
                ('CompanyLeaveApplication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyleaveapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualLeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Annual_Leaves', models.IntegerField(blank=True, default=1, null=0)),
                ('utilised_leaves', models.IntegerField(blank=True, default=0, null=0)),
                ('carried_forward_leaves', models.IntegerField(blank=True, default=0, null=0)),
                ('in_mbl', models.IntegerField(blank=True, default=1, null=0)),
                ('Year', models.DateField(blank=True, null=0)),
                ('CompanyLeaveApplication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyleaveapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveTypesEligiblity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('added_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addedby', to='HRM_App.employeedatamodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='HRM_App.employeedatamodel')),
                ('LeaveType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leavestypedetailmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick_leave', 'sick_leave'), ('annual_leave', 'annual_leave'), ('casual_leave', 'casual_leave')], max_length=50)),
                ('from_date', models.DateField()),
                ('from_session', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM'), ('FULL', 'Full Day')], max_length=10, null=True)),
                ('to_date', models.DateField()),
                ('to_session', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM'), ('FULL', 'Full Day')], max_length=10, null=True)),
                ('days', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('cancled', 'Cancled'), ('pending', 'Pending')], max_length=10, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('LeaveType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeleavetypeseligiblity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approver', to='HRM_App.employeedatamodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('report_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_manager', to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('decription', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('added_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leavetypesmodel'),
        ),
        migrations.CreateModel(
            name='Loss_Off_PayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOP_Leaves', models.IntegerField(blank=True, null=True)),
                ('Year', models.DateField(blank=True, null=True)),
                ('CompanyLeaveApplication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyleaveapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SickLeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sick_Leaves', models.IntegerField(blank=True, default=1, null=True)),
                ('utilised_leaves', models.IntegerField(blank=True, default=0, null=True)),
                ('carried_forward_leaves', models.IntegerField(blank=True, default=0, null=True)),
                ('in_mbl', models.IntegerField(blank=True, default=1, null=True)),
                ('unpaid_leaves', models.IntegerField(blank=True, default=0, null=True)),
                ('Year', models.DateField(blank=True, null=True)),
                ('CompanyLeaveApplication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyleaveapplicationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UnpaidLeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unpaid_Leaves', models.IntegerField(blank=True, null=True)),
                ('Year', models.DateField(blank=True, null=True)),
                ('CompanyLeaveApplication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyleaveapplicationmodel')),
            ],
        ),
    ]
