# Generated by Django 5.0.3 on 2024-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='earned_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='max_carry_forward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
