# Generated by Django 5.0.3 on 2024-06-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0002_leavestypedetailmodel_carry_forward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequestform',
            name='LeaveType',
        ),
        migrations.RemoveField(
            model_name='leaverequestform',
            name='leave_type',
        ),
    ]
