# Generated by Django 5.0.3 on 2024-06-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0003_remove_leaverequestform_leavetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='LeaveType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeleavetypeseligiblity'),
        ),
    ]
