# Generated by Django 5.0.3 on 2024-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0004_leaverequestform_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
