# Generated by Django 5.0.3 on 2024-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0005_leaverequestform_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='carry_forward_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='no_of_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='utilised_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
