# Generated by Django 5.0.3 on 2024-06-25 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0090_alter_candidateapplicationmodel_final_results'),
        ('LMS_App', '0006_employeeleavetypeseligiblity_carry_forward_leaves_and_more'),
    ]

    operations = [
    	
        
        migrations.CreateModel(
            name='MonthWiseLeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.DateField(blank=True, null=True)),
                ('leaves_count_per_month', models.IntegerField()),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.localtime, null=True)),
                ('emp_Applicable_LT_Inst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeleavetypeseligiblity')),
            ],
        ),
    ]
