# Generated by Django 5.0.3 on 2024-06-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0007_employeeleavetypeseligiblity_available_leaves_and_more'),
    ]

    