# Generated by Django 5.0.3 on 2024-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0008_remove_employeeleavetypeseligiblity_carry_forward_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthwiseleavesmodel',
            name='leaves_count_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
