# Generated by Django 5.0.3 on 2024-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0009_alter_monthwiseleavesmodel_leaves_count_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequestform',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
