# Generated by Django 5.0.3 on 2024-06-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0094_remove_interviewschedule_intrview_target'),
        ('LMS_App', '0010_alter_leaverequestform_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetypesmodel',
            old_name='decription',
            new_name='description',
        ),
        migrations.CreateModel(
            name='CompanyAttendanceDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, max_length=100, null=True)),
                ('Shift', models.CharField(blank=True, max_length=100, null=True)),
                ('InTime', models.TimeField(blank=True, null=True)),
                ('LunchIn', models.TimeField(blank=True, null=True)),
                ('LunchOut', models.TimeField(blank=True, null=True)),
                ('OutTime', models.TimeField(blank=True, null=True)),
                ('Hours_Worked', models.TimeField(blank=True, null=True)),
                ('Over_Time', models.TimeField(blank=True, null=True)),
                ('TotalWorkingHours', models.TimeField(blank=True, null=True)),
                ('Late_Arrivals', models.TimeField(blank=True, null=True)),
                ('Early_Depature', models.TimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Emp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
