# Generated by Django 5.0.3 on 2024-06-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0011_rename_decription_leavetypesmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='applicable_to',
            field=models.CharField(blank=True, choices=[('probationer', 'Probationer'), ('confirmed', 'confirmed')], max_length=100, null=True),
        ),
    ]
