# Generated by Django 5.0.3 on 2024-06-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0012_leavestypedetailmodel_applicable_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavetypeseligiblity',
            name='LeaveType',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leavestypedetailmodel'),
        ),
        migrations.AlterField(
            model_name='leavestypedetailmodel',
            name='applicable_to',
            field=models.CharField(blank=True, choices=[('probationer', 'Probationer'), ('confirmed', 'confirmed'), ('both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leavestypedetailmodel',
            name='leave_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leavetypesmodel'),
        ),
    ]
