# Generated by Django 5.0.3 on 2024-06-28 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0013_alter_employeeleavetypeseligiblity_leavetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScanTimings', models.TimeField()),
                ('Created_Date', models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True)),
                ('Attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyattendancedatamodel')),
            ],
        ),
    ]
