# Generated by Django 5.0.3 on 2024-06-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0014_companyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='Status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
