# Generated by Django 5.0.3 on 2024-06-29 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0015_alter_companyattendancedatamodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavetypeseligiblity',
            name='LeaveType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leavestypedetailmodel'),
        ),
    ]
