# Generated by Django 5.0.3 on 2024-06-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0016_alter_employeeleavetypeseligiblity_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
