# Generated by Django 5.0.3 on 2024-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0017_employeeleavetypeseligiblity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to='Leave_Profs/'),
        ),
    ]
