# Generated by Django 5.0.3 on 2024-06-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0018_leaverequestform_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
