# Generated by Django 5.0.3 on 2024-07-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0019_leavestypedetailmodel_is_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='Leave_Withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='Withdrawn_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
