# Generated by Django 5.0.3 on 2024-07-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0020_leaverequestform_leave_withdrawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequestform',
            name='approved_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('cancled', 'Cancled'), ('pending', 'Pending')], max_length=10, null=True),
        ),
    ]
