# Generated by Django 5.0.3 on 2024-07-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0021_alter_leaverequestform_approved_status'),
    ]

    