# Generated by Django 5.0.3 on 2024-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0022_alter_employeeleavetypeseligiblity_available_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='hr_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='is_approved_by_hr',
            field=models.BooleanField(default=False),
        ),
    ]
