# Generated by Django 5.0.3 on 2024-07-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0023_leaverequestform_hr_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='is_details_added',
            field=models.BooleanField(default=True),
        ),
    ]
