# Generated by Django 5.0.3 on 2024-07-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0024_employeeleavetypeseligiblity_is_details_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavetypeseligiblity',
            name='is_details_added',
            field=models.BooleanField(default=False),
        ),
    ]
