# Generated by Django 5.0.3 on 2024-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0025_alter_employeeleavetypeseligiblity_is_details_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='is_utlilised_in_this_month',
            field=models.BooleanField(default=False),
        ),
    ]
