# Generated by Django 5.0.3 on 2024-07-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0026_employeeleavetypeseligiblity_is_utlilised_in_this_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleavetypeseligiblity',
            old_name='is_utlilised_in_this_month',
            new_name='is_utilised_in_this_month',
        ),
    ]
