# Generated by Django 5.0.3 on 2024-07-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0027_rename_is_utlilised_in_this_month_employeeleavetypeseligiblity_is_utilised_in_this_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='applicable_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetypesmodel',
            name='applicable_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavestypedetailmodel',
            name='applicable_to',
            field=models.CharField(blank=True, choices=[('probationer', 'Probationer'), ('confirmed', 'Confirmed'), ('both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leavestypedetailmodel',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leavetypesmodel'),
        ),
    ]
