# Generated by Django 5.0.3 on 2024-07-02 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0102_remove_employeeinformation_employeeweekoffs'),
        ('LMS_App', '0028_leavestypedetailmodel_applicable_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRestrictedLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_utilised', models.BooleanField(default=False)),
                ('utilised_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                
            ],
        ),
    ]


