# Generated by Django 5.0.3 on 2024-07-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0029_availablerestrictedleaves'),
    ]

    
