# Generated by Django 5.0.3 on 2024-07-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0030_leaverequestform_restricted_leave_type'),
    ]

    