# Generated by Django 5.0.3 on 2024-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0031_rename_relision_companyholidaysdatamodel_religion'),
    ]

    