# Generated by Django 5.0.3 on 2024-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0032_companyholidaysdatamodel_leave_type'),
    ]

    
