# Generated by Django 5.0.3 on 2024-07-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0102_remove_employeeinformation_employeeweekoffs'),
        ('LMS_App', '0033_alter_companyholidaysdatamodel_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='Status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('week_off', 'week_off'), ('restricted_leave', 'restricted_leave')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeWeekoffsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekoff_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
