# Generated by Django 5.0.3 on 2024-07-03 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
        ('LMS_App', '0034_alter_companyattendancedatamodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekOffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeweekoffsmodel',
            name='weekoff_day',
        ),
        migrations.AddField(
            model_name='employeeweekoffsmodel',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeeweekoffsmodel',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeeweekoffsmodel',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekoffs', to='HRM_App.employeedatamodel'),
        ),
        migrations.AddField(
            model_name='employeeweekoffsmodel',
            name='weekoff_days',
            field=models.ManyToManyField(related_name='employees', to='LMS_App.weekoffday'),
        ),
    ]
