# Generated by Django 5.0.3 on 2024-07-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0035_weekoffday_remove_employeeweekoffsmodel_weekoff_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeweekoffsmodel',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
