# Generated by Django 5.0.3 on 2024-07-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
        ('LMS_App', '0036_alter_employeeweekoffsmodel_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeweekoffsmodel',
            unique_together={('employee_id', 'month', 'year')},
        ),
    ]
