# Generated by Django 5.0.3 on 2024-07-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0037_alter_employeeweekoffsmodel_unique_together'),
    ]

    