# Generated by Django 5.0.3 on 2024-07-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0038_availablerestrictedleaves_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casualleavesmodel',
            name='CompanyLeaveApplication',
        ),
        migrations.RemoveField(
            model_name='companyleaveapplicationmodel',
            name='EmployeeId',
        ),
        migrations.RemoveField(
            model_name='loss_off_paymodel',
            name='CompanyLeaveApplication',
        ),
        migrations.RemoveField(
            model_name='sickleavesmodel',
            name='CompanyLeaveApplication',
        ),
        migrations.RemoveField(
            model_name='unpaidleavesmodel',
            name='CompanyLeaveApplication',
        ),
        migrations.DeleteModel(
            name='AnnualLeavesModel',
        ),
        migrations.DeleteModel(
            name='CasualLeavesModel',
        ),
        migrations.DeleteModel(
            name='Loss_Off_PayModel',
        ),
        migrations.DeleteModel(
            name='SickLeavesModel',
        ),
        migrations.DeleteModel(
            name='CompanyLeaveApplicationModel',
        ),
        migrations.DeleteModel(
            name='UnpaidLeavesModel',
        ),
    ]
