# Generated by Django 5.0.3 on 2024-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0039_remove_casualleavesmodel_companyleaveapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyattendancedatamodel',
            name='Shift',
        ),
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='Status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('week_off', 'week_off'), ('restricted_leave', 'restricted_leave'), ('public_leave', 'public_leave')], max_length=100, null=True),
        ),
    ]
