# Generated by Django 5.0.3 on 2024-07-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
        ('LMS_App', '0040_remove_companyattendancedatamodel_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendancedatamodel',
            name='Shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeeshifts_model'),
        ),
    ]
