# Generated by Django 5.0.3 on 2024-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0041_companyattendancedatamodel_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='Status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('week_off', ' Week off'), ('restricted_leave', 'Restricted Leave'), ('public_leave', 'Public Leave')], max_length=100, null=True),
        ),
    ]
