# Generated by Django 5.0.3 on 2024-07-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0042_alter_companyattendancedatamodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesLeavesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fall_under', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.leaverequestform')),
            ],
        ),
    ]
