# Generated by Django 5.0.3 on 2024-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0043_employeesleavesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendancedatamodel',
            name='leave_information',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('informed', 'Absent'), ('uninformed', 'Half Day')], max_length=100, null=True),
        ),
    ]
