# Generated by Django 5.0.3 on 2024-07-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0044_companyattendancedatamodel_leave_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='leave_information',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('informed', 'Informed'), ('uninformed', 'Uninformed')], max_length=100, null=True),
        ),
    ]
