# Generated by Django 5.0.3 on 2024-07-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0045_alter_companyattendancedatamodel_leave_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyattendancedatamodel',
            name='Over_Time',
        ),
    ]
