# Generated by Django 5.0.3 on 2024-07-08 09:17

import LMS_App.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0103_delete_employeeweekoffs_model'),
        ('LMS_App', '0046_remove_companyattendancedatamodel_over_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalInvitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvitationId', models.CharField(default=LMS_App.models.AppraisalInvitation_Id, max_length=100)),
                ('strat_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('filled_on', models.DateField(blank=True, null=True)),
                ('invited_on', models.DateField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('EmployeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REVIEW_PERIOD', models.CharField(max_length=255)),
                ('DATE_OF_REVIEW', models.DateField()),
                ('works_to_full_potential', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('quality_of_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('work_consistency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('independent_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('takes_initiative', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('group_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('productivity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('creativity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('honesty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('integrity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('coworker_relations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('client_relations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('technical_skills', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('dependability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('punctuality', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('attendance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('key_responsibilities', models.TextField()),
                ('performance_assessment_responsibilities', models.TextField()),
                ('performance_and_work_objectives', models.TextField()),
                ('performance_assessment_objectives', models.TextField()),
                ('core_values_assessment', models.TextField()),
                ('employee_signature', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('Employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('invitation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_App.appraisalinvitationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSelfEvaluationReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCurrentReview', models.DateField(blank=True, null=True)),
                ('DateOfLastReview', models.DateField(blank=True, null=True)),
                ('Reviewer_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('works_to_full_potential', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('quality_of_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('work_consistency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('independent_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('takes_initiative', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('group_work', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('productivity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('creativity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('honesty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('integrity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('coworker_relations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('client_relations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('technical_skills', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('dependability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('punctuality', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('attendance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('Were_previously_set_goals_achieved', models.TextField(blank=True, null=True)),
                ('Goals_for_next_review_period', models.TextField(blank=True, null=True)),
                ('COMMENTS_AND_APPROVAL', models.TextField(blank=True, null=True)),
                ('submitted_Date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('EmployeeSelfEvaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprasial_review', to='LMS_App.employeeselfevaluation')),
                ('Reviewer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='MettingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts_status', models.CharField(max_length=100)),
                ('Meating_Date', models.DateTimeField(blank=True, null=True)),
                ('mail_sent_status', models.BooleanField(default=False)),
                ('Meatting_reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('percentage_of_increment', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('EmployeeSelfEvaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeselfevaluation')),
                ('Meatting_reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Metrics_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metric_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField()),
                ('Target_Goal', models.TextField()),
                ('Performance_Achived', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=100, null=True)),
                ('Achived_Date', models.DateField(blank=True, null=True)),
                ('Performance_Rating', models.IntegerField(blank=True, null=True)),
                ('Comments_Feedback', models.TextField()),
                ('Goals_for_Next_Period', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('EmployeeSelfEvaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeselfevaluation')),
            ],
        ),
    ]
