# Generated by Django 5.0.3 on 2024-07-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0047_appraisalinvitationmodel_employeeselfevaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='leave_information',
            field=models.CharField(blank=True, choices=[('No_attention_required', 'No_attention_required'), ('Authorized_Absent', 'Authorized_Absent'), ('Unauthorized_Absent', 'Unauthorized_Absent')], max_length=100, null=True),
        ),
    ]
