# Generated by Django 5.0.3 on 2024-07-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0048_alter_companyattendancedatamodel_leave_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesleavesmodel',
            name='eligible_leave_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeleavetypeseligiblity'),
        ),
    ]
