# Generated by Django 5.0.3 on 2024-07-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0049_employeesleavesmodel_eligible_leave_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='approve_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
