# Generated by Django 5.0.3 on 2024-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0050_leaverequestform_approve_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequestform',
            name='approved_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=10, null=True),
        ),
    ]
