# Generated by Django 5.0.3 on 2024-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0051_alter_leaverequestform_approved_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequestform',
            old_name='reason',
            new_name='hr_reason',
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='rm_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
