# Generated by Django 5.0.3 on 2024-07-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0052_rename_reason_leaverequestform_hr_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequestform',
            name='approve_reason',
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
