# Generated by Django 5.0.3 on 2024-07-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0053_remove_leaverequestform_approve_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='is_approved_by_rm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='rm_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
