# Generated by Django 5.0.3 on 2024-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0054_leaverequestform_is_approved_by_rm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='hr_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='rm_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
