# Generated by Django 5.0.3 on 2024-07-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0055_leaverequestform_hr_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalinvitationmodel',
            name='active_status',
        ),
    ]
