# Generated by Django 5.0.3 on 2024-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0056_remove_appraisalinvitationmodel_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalinvitationmodel',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
