# Generated by Django 5.0.3 on 2024-07-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0057_appraisalinvitationmodel_active_status'),
    ]

    
