# Generated by Django 5.0.3 on 2024-07-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0066_alter_employeepersonalinformation_international_employee_and_more'),
        ('LMS_App', '0058_remove_companyholidaysdatamodel_religion'),
    ]

    