# Generated by Django 5.0.3 on 2024-07-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0059_companyholidaysdatamodel_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='EmployeeSelfEvaluation',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='works_to_full_potential',
        ),
        migrations.AlterField(
            model_name='employeeselfevaluation',
            name='invitation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.appraisalinvitationmodel'),
        ),
        migrations.DeleteModel(
            name='MettingReview',
        ),
    ]
