# Generated by Django 5.0.3 on 2024-07-26 10:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0130_employeedatamodel_verified_by'),
        ('LMS_App', '0060_remove_employeeselfevaluationreviewmodel_employeeselfevaluation_and_more'),
    ]

    operations = [
      
        
        migrations.CreateModel(
            name='MettingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contracts_status', models.CharField(max_length=100)),
                ('Meating_Date', models.DateTimeField(blank=True, null=True)),
                ('mail_sent_status', models.BooleanField(default=False)),
                ('Meatting_reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('percentage_of_increment', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('EmployeeSelfEvaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeselfevaluation')),
                ('Meatting_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
