# Generated by Django 5.0.3 on 2024-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0062_alter_employeeselfevaluationreviewmodel_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalinvitationmodel',
            name='filled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalinvitationmodel',
            name='invited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
