# Generated by Django 5.0.3 on 2024-07-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0063_alter_appraisalinvitationmodel_filled_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeselfevaluation',
            name='employee_signature',
            field=models.ImageField(blank=True, upload_to='EmployeeDocuments/appraisal_signature/'),
        ),
    ]
