# Generated by Django 5.0.3 on 2024-07-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0064_alter_employeeselfevaluation_employee_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluation',
            name='Employee_ID',
        ),
    ]
