# Generated by Django 5.0.3 on 2024-07-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0130_employeedatamodel_verified_by'),
        ('LMS_App', '0065_remove_employeeselfevaluation_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='assigning_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigning_person', to='HRM_App.employeedatamodel'),
        ),
    ]
