# Generated by Django 5.0.3 on 2024-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0067_alter_employeeselfevaluation_date_of_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalinvitationmodel',
            name='is_rm_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appraisalinvitationmodel',
            name='rm_filled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
