# Generated by Django 5.0.3 on 2024-07-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0130_employeedatamodel_verified_by'),
        ('LMS_App', '0068_appraisalinvitationmodel_is_rm_filled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_metrics_model',
            name='Achived_Date',
        ),
        migrations.RemoveField(
            model_name='performance_metrics_model',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='performance_metrics_model',
            name='Metric_Name',
        ),
        migrations.RemoveField(
            model_name='performance_metrics_model',
            name='Target_Goal',
        ),
        migrations.AddField(
            model_name='performance_metrics_model',
            name='Areas_for_Improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance_metrics_model',
            name='Meeting_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance_metrics_model',
            name='Meeting_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel'),
        ),
        migrations.AddField(
            model_name='performance_metrics_model',
            name='Potential_Development_Opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance_metrics_model',
            name='Responsible_Parties',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performance_metrics_model',
            name='Strengths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
