# Generated by Django 5.0.3 on 2024-07-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0069_remove_performance_metrics_model_achived_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MettingReview',
        ),
    ]
