# Generated by Django 5.0.3 on 2024-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0070_delete_mettingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance_metrics_model',
            name='meeting_mail_sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
