# Generated by Django 5.0.3 on 2024-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0071_performance_metrics_model_meeting_mail_sent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_metrics_model',
            name='Comments_Feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance_metrics_model',
            name='Goals_for_Next_Period',
            field=models.TextField(blank=True, null=True),
        ),
    ]
