# Generated by Django 5.0.3 on 2024-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0072_alter_performance_metrics_model_comments_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_metrics_model',
            name='meeting_mail_sent_status',
        ),
        migrations.AddField(
            model_name='appraisalinvitationmodel',
            name='meeting_mail_sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
