# Generated by Django 5.0.3 on 2024-07-27 16:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0070_remove_companyemployeespositionhistory_employment_type_and_more'),
        ('HRM_App', '0131_employeeinformation_employeement_type_and_more'),
        ('LMS_App', '0073_remove_performance_metrics_model_meeting_mail_sent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavetypeseligiblity',
            name='carry_forward_leaves',
        ),
        migrations.AddField(
            model_name='appraisalinvitationmodel',
            name='invitation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='Available_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='no_of_leaves_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='EmployeeSelfEvaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprasial_review', to='LMS_App.employeeselfevaluation'),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='works_to_full_potential',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='employeeleavetypeseligiblity',
            name='utilised_leaves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employeeselfevaluationreviewmodel',
            name='quality_of_work',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='applied_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestform',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance_metrics_model',
            name='EmployeeSelfEvaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.employeeselfevaluation'),
        ),
        migrations.CreateModel(
            name='AvailableRestrictedLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_utilised', models.BooleanField(default=False)),
                ('utilised_date', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequestform',
            name='restricted_leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.availablerestrictedleaves'),
        ),
        migrations.CreateModel(
            name='CompanyHolidaysDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OccasionName', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_type', models.CharField(blank=True, choices=[('Public_Leave', 'Public_Leave'), ('Restricted_Leave', 'Restricted_Leave')], max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('Religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.religionmodels')),
                ('added_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='availablerestrictedleaves',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyholidaysdatamodel'),
        ),
    ]
