# Generated by Django 5.0.3 on 2024-07-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0074_remove_employeeleavetypeseligiblity_carry_forward_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavetypeseligiblity',
            name='no_of_leaves',
        ),
    ]
