# Generated by Django 5.0.3 on 2024-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0076_remove_employeeleavetypeseligiblity_utilised_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavetypeseligiblity',
            name='utilised_leaves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
