# Generated by Django 5.0.3 on 2024-07-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0078_employeeleavetypeseligiblity_no_of_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyholidaysdatamodel',
            name='Religion',
        ),
    ]
