# Generated by Django 5.0.3 on 2024-07-28 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_App', '0070_remove_companyemployeespositionhistory_employment_type_and_more'),
        ('LMS_App', '0079_remove_companyholidaysdatamodel_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholidaysdatamodel',
            name='Religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS_App.religionmodels'),
        ),
    ]
