# Generated by Django 5.0.3 on 2024-07-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0080_companyholidaysdatamodel_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyholidaysdatamodel',
            name='leave_type',
        ),
    ]
