# Generated by Django 5.0.3 on 2024-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0081_remove_companyholidaysdatamodel_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholidaysdatamodel',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Public_Leave', 'Public_Leave'), ('Restricted_Leave', 'Restricted_Leave')], max_length=100, null=True),
        ),
    ]
