# Generated by Django 5.0.3 on 2024-07-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0082_companyholidaysdatamodel_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequestform',
            name='restricted_leave_type',
        ),
        migrations.DeleteModel(
            name='AvailableRestrictedLeaves',
        ),
    ]
