# Generated by Django 5.0.3 on 2024-07-28 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0131_employeeinformation_employeement_type_and_more'),
        ('LMS_App', '0083_remove_leaverequestform_restricted_leave_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRestrictedLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_utilised', models.BooleanField(default=False)),
                ('utilised_date', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM_App.employeedatamodel')),
                ('holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.companyholidaysdatamodel')),
            ],
        ),
    ]
