# Generated by Django 5.0.3 on 2024-07-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0084_availablerestrictedleaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestform',
            name='restricted_leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS_App.availablerestrictedleaves'),
        ),
    ]
