# Generated by Django 5.0.3 on 2024-07-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0085_leaverequestform_restricted_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='EmployeeSelfEvaluation',
        ),
    ]
