# Generated by Django 5.0.3 on 2024-07-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0086_remove_employeeselfevaluationreviewmodel_employeeselfevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='EmployeeSelfEvaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apprasial_review', to='LMS_App.employeeselfevaluation'),
        ),
    ]
