# Generated by Django 5.0.3 on 2024-07-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0087_employeeselfevaluationreviewmodel_employeeselfevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='COMMENTS_AND_APPROVAL',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='Goals_for_next_review_period',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='Were_previously_set_goals_achieved',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='client_relations',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='coworker_relations',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='dependability',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='group_work',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='honesty',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='independent_work',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='integrity',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='productivity',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='quality_of_work',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='submitted_Date',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='takes_initiative',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='work_consistency',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='works_to_full_potential',
        ),
    ]
