# Generated by Django 5.0.3 on 2024-07-28 07:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0088_remove_employeeselfevaluationreviewmodel_comments_and_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='COMMENTS_AND_APPROVAL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='Goals_for_next_review_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='Were_previously_set_goals_achieved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='attendance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='client_relations',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='communication',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='coworker_relations',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='creativity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='dependability',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='group_work',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='honesty',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='independent_work',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='integrity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='productivity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='punctuality',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='quality_of_work',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='submitted_Date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='takes_initiative',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='technical_skills',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='work_consistency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='works_to_full_potential',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
