# Generated by Django 5.0.3 on 2024-07-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0091_employeeselfevaluationreviewmodel_comments_and_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='COMMENTS_AND_APPROVAL',
        ),
    ]
