# Generated by Django 5.0.3 on 2024-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0092_remove_employeeselfevaluationreviewmodel_comments_and_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='COMMENTS_AND_APPROVAL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
