# Generated by Django 5.0.3 on 2024-07-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0095_employeeselfevaluationreviewmodel_comments_and_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='works_to_full_potential',
        ),
    ]
