# Generated by Django 5.0.3 on 2024-07-28 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0096_remove_employeeselfevaluationreviewmodel_works_to_full_potential'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='works_to_full_potential',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
