# Generated by Django 5.0.3 on 2024-07-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0099_employeeselfevaluationreviewmodel_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='client_relations',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='coworker_relations',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='creativity',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='dependability',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='group_work',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='honesty',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='independent_work',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='integrity',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='productivity',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='takes_initiative',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='work_consistency',
        ),
    ]
