# Generated by Django 5.0.3 on 2024-07-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0101_employeeselfevaluationreviewmodel_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeselfevaluationreviewmodel',
            name='attendance',
        ),
    ]
