# Generated by Django 5.0.3 on 2024-07-28 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0102_remove_employeeselfevaluationreviewmodel_attendance'),
    ]

    