# Generated by Django 5.0.3 on 2024-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0104_employeeselfevaluationreviewmodel_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeselfevaluation',
            name='overall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeselfevaluationreviewmodel',
            name='overall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance_metrics_model',
            name='Performance_Achived',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Verygood', 'Verygood'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=100, null=True),
        ),
    ]
