# Generated by Django 5.0.3 on 2024-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0105_employeeselfevaluation_overall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholidaysdatamodel',
            name='related_image',
            field=models.ImageField(blank=True, null=True, upload_to='holidaysrelated/'),
        ),
    ]
