# Generated by Django 5.0.3 on 2024-10-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0106_companyholidaysdatamodel_related_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyholidaysdatamodel',
            name='related_image',
        ),
    ]
