# Generated by Django 5.0.3 on 2024-10-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0107_remove_companyholidaysdatamodel_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyholidaysdatamodel',
            name='related_image',
            field=models.ImageField(blank=True, null=True, upload_to='holidaysrelated/'),
        ),
    ]
