# Generated by Django 5.0.3 on 2024-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0108_companyholidaysdatamodel_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestypedetailmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
