# Generated by Django 5.0.3 on 2025-02-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0109_leavestypedetailmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyattendance',
            name='ScanType',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyattendancedatamodel',
            name='break_timings',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyattendancedatamodel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
