# Generated by Django 5.0.3 on 2025-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0110_companyattendance_scantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyattendancedatamodel',
            name='leave_information',
            field=models.CharField(blank=True, choices=[('No_attention_required', 'No_attention_required'), ('Attention_required', 'Attention_required'), ('Authorized_Absent', 'Authorized_Absent'), ('Unauthorized_Absent', 'Unauthorized_Absent')], max_length=100, null=True),
        ),
    ]
