# Generated by Django 5.0.3 on 2025-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0160_employeeinformation_wfh_status_and_more'),
        ('LMS_App', '0111_alter_companyattendancedatamodel_leave_information'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companyattendancedatamodel',
            constraint=models.UniqueConstraint(fields=('Emp_Id', 'date'), name='unique_employee_attendance'),
        ),
    ]
