# Generated by Django 5.2.8 on 2025-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0112_companyattendancedatamodel_unique_employee_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Description_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Job_Discription', models.TextField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('company_inrto', models.TextField(blank=True, null=True)),
                ('department_id', models.CharField(blank=True, max_length=100, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('designation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_points', models.JSONField(blank=True, default=list, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('key_skills', models.JSONField(blank=True, default=list, null=True)),
                ('max_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('min_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('min_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.JSONField(blank=True, default=list, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
