# Generated by Django 5.2.8 on 2025-12-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0113_job_description_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_description_model',
            old_name='created_at',
            new_name='posted_on',
        ),
    ]
