# Generated by Django 5.2.8 on 2025-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0114_rename_created_at_job_description_model_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_description_model',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
