# Generated by Django 5.2.8 on 2026-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0115_job_description_model_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_description_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
