# Generated by Django 5.2.8 on 2026-02-02 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_App', '0175_newdailyachivesmodel_client_company_name_and_more'),
        ('LMS_App', '0116_job_description_model_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('week_off', ' Week off'), ('restricted_leave', 'Restricted Leave'), ('public_leave', 'Public Leave'), ('less_than_half_day', 'Less Than Half Day')], max_length=50, null=True)),
                ('requested_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('week_off', ' Week off'), ('restricted_leave', 'Restricted Leave'), ('public_leave', 'Public Leave'), ('less_than_half_day', 'Less Than Half Day')], max_length=50)),
                ('reason', models.TextField()),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('approval_reason', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to='HRM_App.employeedatamodel')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='LMS_App.companyattendancedatamodel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests_made', to='HRM_App.employeedatamodel')),
            ],
        ),
    ]
