# Generated by Django 5.2.8 on 2026-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_App', '0117_attendancecorrectionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDataPreparationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_by', models.CharField(blank=True, default='auto_payslip_generation', max_length=100, null=True)),
                ('record_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Attendance Preparation Log',
                'verbose_name_plural': 'Attendance Preparation Logs',
                'unique_together': {('month', 'year')},
            },
        ),
    ]
