"""
Django settings for tution_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kult4_a%j_gvq4^bq4$#x*^zwr(aucg!_$4l$tvy3gexd-w^v7'

# Shared JWT Secret Key for SSO (MUST match HRM project)
SSO_SHARED_SECRET = 'sso-shared-secret-key-hrm-das-2026'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.18.40']


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be at top for WebSocket support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'channels',  # WebSocket support
    'schedular',    
]

AUTH_USER_MODEL = 'schedular.User'

# Custom authentication backend to use email instead of username
AUTHENTICATION_BACKENDS = [
    'schedular.backends.EmailBackend',
]


REST_FRAMEWORK = {
    # AUTHENTICATION ENABLED FOR PRODUCTION
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "schedular.authentication.ImpersonationJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # Require authentication
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'schedular.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 10,
    # Datetime formatting - ensures timezone-aware datetimes are returned in Asia/Kolkata
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S', 'iso-8601'],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SSO_SHARED_SECRET,  # Use shared secret for SSO
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'DAS',
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}

# ASGI Application for WebSocket support
ASGI_APPLICATION = 'activity.asgi.application'

# Channel Layers Configuration
CHANNEL_LAYERS = {
    'default': {
        # Development: In-memory channel layer
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
        
        # Production: Use Redis (uncomment when deploying)
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        # 'CONFIG': {
        #     "hosts": [('127.0.0.1', 6379)],
        # },
    },
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "anandappu200377@gmail.com"
EMAIL_HOST_PASSWORD = "ugop trqv etzr meuk"   # Use App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = "anandappu200377@gmail.com"
DEFAULT_ADMIN_EMAIL = ADMIN_EMAIL

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'schedular.middleware.EmployeeStatusCheckMiddleware',  # SSO Employee Status Check
]

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.18.40:3000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.18.40:63105",
    "http://localhost:63105",
]

# For development, allow all localhost origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://192\.168\.18\.40:\d+$",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-impersonate-user', # Added to allow impersonation header
]

ROOT_URLCONF = 'activity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'activity.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Force Django to use local timezone for datetime rendering
USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─── HRM Integration Settings ─────────────────────────────────────────────────
# HRM Backend URL for employee synchronization and code validation
# IMPORTANT: Update this to your production HRM backend URL
# For local development: http://127.0.0.1:8001
# For production: Use environment variable or update with actual URL
import os
HRM_BASE_URL = os.getenv('HRM_BASE_URL', 'http://127.0.0.1:8001')  # Localhost HRM
# HRM_BASE_URL = os.getenv('HRM_BASE_URL', 'https://hrmbackendapi.meridahr.com')  # Production
# DAS Frontend URL for SSO redirects
# IMPORTANT: Update this to your production DAS frontend URL
# For local development: http://localhost:63105/
# For production: https://das.meridahr.com/ (or your actual DAS frontend URL)
DAS_FRONTEND_URL = os.getenv('DAS_FRONTEND_URL', 'http://127.0.0.1:63105/')
# DAS_FRONTEND_URL = os.getenv('DAS_FRONTEND_URL', 'https://das.meridahr.com/')

# SSL Verification setting for HRM requests
# Set to True for production, False for local dev if encountering SSL errors
VERIFY_SSL_HRM = os.getenv('VERIFY_SSL_HRM', 'False').lower() == 'true'

